use std::{env,thread,time::Instant};
#[derive(Clone,Copy)] struct Bar{open:f64,high:f64,low:f64,close:f64}
#[derive(Default,Clone,Copy)] struct Out{trades:u64,pnl:f64,checksum:u64}
fn data(n:usize)->Vec<Bar>{let mut v=Vec::with_capacity(n);let mut p=100.;for i in 0..n{let x=((i as f64)*0.017).sin()*0.004+((i as f64)*0.003).cos()*0.002;p*=1.+x;let r=0.0015+((i%97)as f64)*0.00001;v.push(Bar{open:p,high:p*(1.+r),low:p*(1.-r),close:p*(1.+x*0.3)});}v}
fn ind(b:&[Bar])->(Vec<f64>,Vec<f64>,Vec<f64>){let n=b.len();let(mut e,mut r,mut a)=(vec![0.;n],vec![50.;n],vec![0.;n]);let(mut ag,mut al,mut at)=(0.,0.,0.);e[0]=b[0].close;for i in 1..n{e[i]=e[i-1]+(b[i].close-e[i-1])*2./21.;let d=b[i].close-b[i-1].close;ag=(ag*13.+d.max(0.))/14.;al=(al*13.+(-d).max(0.))/14.;r[i]=if al==0.{100.}else{100.-100./(1.+ag/al)};let tr=(b[i].high-b[i].low).max((b[i].high-b[i-1].close).abs()).max((b[i].low-b[i-1].close).abs());at=(at*13.+tr)/14.;a[i]=at;}(e,r,a)}
fn one(id:usize,b:&[Bar],e:&[f64],r:&[f64],a:&[f64])->Out{let mut o=Out::default();let(mut pos,mut entry,mut sl,mut tp)=(false,0.,0.,0.);let th=35.+(id%25)as f64;for i in 21..b.len()-1{if pos{let x=&b[i];let exit=if x.low<=sl{sl}else if x.high>=tp{tp}else{continue};o.pnl+=exit-entry; o.trades+=1;pos=false;}else if b[i].close>e[i]&&r[i]<th{entry=b[i+1].open;sl=entry-a[i]*(1.+(id%3)as f64*0.2);tp=entry+a[i]*(1.5+(id%5)as f64*0.1);pos=true;}}o.checksum=((o.pnl*1e6)as i64 as u64)^o.trades;o}
fn run(workers:usize,candidates:usize,b:&[Bar],e:&[f64],r:&[f64],a:&[f64])->Out{thread::scope(|s|{let mut h=Vec::new();for w in 0..workers{h.push(s.spawn(move||{let mut z=Out::default();for id in (w..candidates).step_by(workers){let q=one(id,b,e,r,a);z.trades+=q.trades;z.pnl+=q.pnl;z.checksum^=q.checksum;}z}));}h.into_iter().map(|x|x.join().unwrap()).fold(Out::default(),|mut x,y|{x.trades+=y.trades;x.pnl+=y.pnl;x.checksum^=y.checksum;x})})}
fn main(){let args:Vec<_>=env::args().collect();let workers=args.get(1).and_then(|x|x.parse().ok()).unwrap_or(1);let candidates=args.get(2).and_then(|x|x.parse().ok()).unwrap_or(1000);let n=10*365*24*60;let t=Instant::now();let b=data(n);let(e,r,a)=ind(&b);let prep=t.elapsed().as_secs_f64();let t=Instant::now();let o=run(workers,candidates,&b,&e,&r,&a);let secs=t.elapsed().as_secs_f64();println!("{{\"workers\":{workers},\"candidates\":{candidates},\"bars\":{n},\"prep_seconds\":{prep:.3},\"seconds\":{secs:.3},\"candidate_backtests_per_second\":{:.3},\"strategy_bar_evals_per_second\":{:.0},\"trades\":{},\"pnl\":{:.6},\"checksum\":{}}}",candidates as f64/secs,candidates as f64*n as f64/secs,o.trades,o.pnl,o.checksum);}
#[cfg(test)] mod t{use super::*;#[test]fn varied(){let b=data(5000);let(e,r,a)=ind(&b);assert_ne!(one(1,&b,&e,&r,&a).checksum,one(2,&b,&e,&r,&a).checksum)}#[test]fn deterministic(){let b=data(5000);let(e,r,a)=ind(&b);assert_eq!(run(1,20,&b,&e,&r,&a).checksum,run(4,20,&b,&e,&r,&a).checksum)}#[test]fn next_open(){let b=[Bar{open:100.,high:101.,low:99.,close:100.},Bar{open:103.,high:104.,low:102.,close:103.}];assert_eq!(b[1].open,103.)}#[test]fn target_hit(){let x=Bar{open:100.,high:102.,low:100.,close:101.};let exit=if x.low<=99.{99.}else if x.high>=101.{101.}else{0.};assert_eq!(exit,101.)}#[test]fn pessimistic(){let x=Bar{open:100.,high:102.,low:98.,close:100.};let exit=if x.low<=99.{99.}else if x.high>=101.{101.}else{0.};assert_eq!(exit,99.)}}
