param([Parameter(Mandatory=$true)][string]$IncomingRoot,[Parameter(Mandatory=$true)][string]$RunId)
$ErrorActionPreference='Stop';$target='macd';$runtime='NoraPhase2MacdRuntimeV3.mqh';$tester='NoraPhase2MacdTesterCanaryV3.mq5';$editor='C:\Program Files\Darwinex MetaTrader 5\MetaEditor64.exe';$expectedVersion='5.0.0.5836';$root="$env:USERPROFILE\NoraPhase2U";$run=Join-Path $root $RunId
function Hash($p){(Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant()};New-Item -ItemType Directory -Force $run|Out-Null;$source=Join-Path $run 'source';New-Item -ItemType Directory -Force $source|Out-Null;$log=Join-Path $run 'compile.log';$ex5=Join-Path $source $tester.Replace('.mq5','.ex5')
function JStr($s){if($null -eq $s){'""'}else{'"'+($s -replace '\\','\\' -replace '"','\"' -replace "`n",'\n' -replace "`r",'\r' -replace "`t",'\t')+'"'}}
function JBool($v){if($v){'true'}else{'false'}}
function JNull($v){if($null -eq $v){'null'}else{JStr $v}}
$record=@{exit=0;reason='';success=$false;state='incomplete';logHash='';ex5Hash='';ex5Size=0;warnings=0;warnLines=@();errors=0;errLines=@();checks=@{};failure='';preexisting=$false;version='';completed='';runtimeHash='';testerHash='';logComplete=$false;sourceBinding=$false;ex5Created='';ex5Modified=''}
try {foreach($n in @($runtime,$tester)){if(!(Test-Path (Join-Path $IncomingRoot $n))){throw "missing source: $n"};Copy-Item (Join-Path $IncomingRoot $n) (Join-Path $source $n) -Force};$program=Join-Path $source $tester;$record.runtimeHash=Hash (Join-Path $source $runtime);$record.testerHash=Hash $program;if(!(Test-Path $editor)){throw 'missing compiler'};$version=(Get-Item $editor).VersionInfo.FileVersion;if($version -ne $expectedVersion){throw 'unexpected MetaEditor version'};$record.version=$version;if(Test-Path $ex5){$record.preexisting=$true;Remove-Item $ex5 -Force};$cArgs=@('/compile:"'+$program+'"','/log:"'+$log+'"');$start=Get-Date;$p=Start-Process -FilePath $editor -ArgumentList $cArgs -PassThru;$p.WaitForExit(120000)|Out-Null;if(!$p.HasExited){$p.Kill();throw 'MetaEditor timeout'};$record.exit=$p.ExitCode;if(!(Test-Path $log)){throw 'missing compiler log'};$record.logHash=Hash $log;$lines=Get-Content $log;$record.warnLines=@($lines|Where-Object {$_ -match '(?i)\bwarning\b'});$record.errLines=@($lines|Where-Object {$_ -match '(?i)\berror\b'});$record.warnings=$record.warnLines.Count;$record.errors=$record.errLines.Count;$record.logComplete=($lines -match 'Result:') -and ($lines -match [regex]::Escape($program));$record.sourceBinding=[bool]($lines -match [regex]::Escape($program));if(!(Test-Path $ex5)){throw 'missing EX5'};$item=Get-Item $ex5;if($item.LastWriteTimeUtc -lt $start.ToUniversalTime()){throw 'stale EX5'};$record.ex5Hash=Hash $ex5;$record.ex5Size=$item.Length;$record.ex5Created=$item.CreationTimeUtc.ToString('o');$record.ex5Modified=$item.LastWriteTimeUtc.ToString('o');$clean=($record.errors -eq 0 -and $record.warnings -eq 0);$record.checks=@{version=($version -eq $expectedVersion);log_complete=$record.logComplete;clean_log=$clean;source_binding=$record.sourceBinding;expected_ex5_path=$true;fresh_ex5=$true};if($record.exit -eq 0){$record.reason='accepted_zero'}elseif($record.exit -eq 1 -and $version -eq $expectedVersion -and $record.logComplete -and $clean){$record.reason='accepted_metaeditor_5836_one'}else{throw 'unexpected or uncorroborated compiler exit'};$record.success=$true;$record.state='completed'}catch{$record.failure=$_.Exception.Message;$record.state='failed'}finally{
$record.completed=(Get-Date).ToUniversalTime().ToString('o')
$warns=($record.warnLines|ForEach-Object{JStr $_}) -join ','
$errs=($record.errLines|ForEach-Object{JStr $_}) -join ','
$chk=$record.checks
$json=@"
{"contract_version":"nora.phase2.compiler_record_v2","compiler_policy_version":"nora.metaeditor_cli_success_v1","target_identifier":"$target","metaeditor_executable_path":$(JStr $editor),"metaeditor_version":$(JStr $record.version),"source_runtime_path":"source/$runtime","source_runtime_sha256":$(JStr $record.runtimeHash),"tester_source_path":"source/$tester","tester_source_sha256":$(JStr $record.testerHash),"command":$(JStr ($editor+' /compile:"'+$program+'" /log:"'+$log+'"')),"arguments":[$(JStr "/compile:`"$program`""),$(JStr "/log:`"$log`"")],"started_utc":$(JStr $record.completed),"raw_process_exit_status":$($record.exit),"normalized_exit_interpretation":$(JStr $record.reason),"exit_interpretation_reason":$(JStr $record.reason),"completion_state":$(JStr $record.state),"compiler_success":$(JBool $record.success),"warning_count":$($record.warnings),"warnings":[$warns],"error_count":$($record.errors),"errors":[$errs],"compiler_log_relative_path":"compile.log","compiler_log_sha256":$(JStr $record.logHash),"compiler_log_complete":$(JBool $record.logComplete),"expected_ex5_relative_path":"source/$($tester.Replace('.mq5','.ex5'))","expected_ex5_absolute_path":$(JStr $ex5),"preexisting_ex5":$(JBool $record.preexisting),"ex5_exists":true,"ex5_creation_utc":$(JStr $record.ex5Created),"ex5_modification_utc":$(JStr $record.ex5Modified),"ex5_size":$($record.ex5Size),"ex5_sha256":$(JStr $record.ex5Hash),"corroborating_checks":{"version":$(JBool $chk.version),"log_complete":$(JBool $chk.log_complete),"clean_log":$(JBool $chk.clean_log),"source_binding":$(JBool $chk.source_binding),"expected_ex5_path":true},"failure_reason":$(JNull $record.failure)}
"@
$jsonPath=Join-Path $run 'compile.json'
[System.IO.File]::WriteAllText($jsonPath,$json,[System.Text.Encoding]::UTF8)
}
if(!$record.success){exit 2}