[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][ValidateSet('remediate','smoke')][string]$Mode,
 [Parameter(Mandatory=$true)][string]$RuleName,
 [Parameter(Mandatory=$true)][string]$ExpectedProgram,
 [Parameter(Mandatory=$true)][string]$ExpectedProgramSha256,
 [Parameter(Mandatory=$true)][string]$RepositoryCommit,
 [string]$PreArtifactPath,
 [string]$ReceiptPath,
 [string]$EvidenceRoot='C:\NoraEvidence\Phase2'
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$authorized='{AE6A1199-33B0-4109-B850-F1BB61AF0F6B}'
function Hash([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Atomic([string]$p,$v){$full=[IO.Path]::GetFullPath($p);$root=[IO.Path]::GetFullPath($EvidenceRoot).TrimEnd('\');if(!$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'artifact outside evidence root'};$parent=Split-Path -Parent $full;New-Item -ItemType Directory -Force -Path $parent|Out-Null;$tmp=$full+'.partial.'+[guid]::NewGuid().ToString('N');[IO.File]::WriteAllText($tmp,($v|ConvertTo-Json -Depth 16 -Compress),[Text.UTF8Encoding]::new($false));$s=[IO.File]::Open($tmp,'Open','ReadWrite','None');$s.Flush($true);$s.Dispose();if(Test-Path $full){throw 'immutable artifact already exists'};[IO.File]::Move($tmp,$full)}
function View([string]$store){$rs=@(Get-NetFirewallRule -PolicyStore $store -Name $RuleName -ErrorAction Stop);if($rs.Count-ne1){throw ('exact rule cardinality: '+$store)};$r=$rs[0];$app=@(Get-NetFirewallApplicationFilter -AssociatedNetFirewallRule $r);$svc=@(Get-NetFirewallServiceFilter -AssociatedNetFirewallRule $r);$addr=@(Get-NetFirewallAddressFilter -AssociatedNetFirewallRule $r);$port=@(Get-NetFirewallPortFilter -AssociatedNetFirewallRule $r);$iface=@(Get-NetFirewallInterfaceTypeFilter -AssociatedNetFirewallRule $r);$sec=@(Get-NetFirewallSecurityFilter -AssociatedNetFirewallRule $r);foreach($pair in @(@('application',$app.Count),@('service',$svc.Count),@('address',$addr.Count),@('port',$port.Count),@('interface',$iface.Count),@('security',$sec.Count))){if($pair[1]-ne1){throw ('ambiguous '+$pair[0]+' filter')}};[ordered]@{store=$store;name=[string]$r.Name;instance_id=[string]$r.InstanceID;display_name=[string]$r.DisplayName;enabled=[string]$r.Enabled;direction=[string]$r.Direction;action=[string]$r.Action;profile=[string]$r.Profile;edge_traversal=[string]$r.EdgeTraversalPolicy;policy_store_source=[string]$r.PolicyStoreSource;policy_store_source_type=[string]$r.PolicyStoreSourceType;program=[string]$app[0].Program;package=[string]$app[0].Package;service=[string]$svc[0].Service;local_address=[string]$addr[0].LocalAddress;remote_address=[string]$addr[0].RemoteAddress;protocol=[string]$port[0].Protocol;local_port=[string]$port[0].LocalPort;remote_port=[string]$port[0].RemotePort;icmp_type=[string]$port[0].IcmpType;interface_type=[string]$iface[0].InterfaceType;authentication=[string]$sec[0].Authentication;encryption=[string]$sec[0].Encryption;override_block_rules=[bool]$sec[0].OverrideBlockRules}}
if($Mode-eq'smoke'){[ordered]@{schema='nora.phase2_exact_rule_remediation_smoke_v1';mutation_cmdlets_invoked=$false;authorized_rule=$authorized}|ConvertTo-Json -Compress;exit 0}
if($RuleName-ne$authorized-or$RuleName-notmatch'^\{[0-9A-F-]{36}\}$'){throw 'unauthorized rule identity'}
if($RepositoryCommit-notmatch'^[0-9a-f]{40}$'-or$ExpectedProgramSha256-notmatch'^[0-9a-f]{64}$'){throw 'invalid identity binding'}
$resolved=(Get-Item -LiteralPath $ExpectedProgram -ErrorAction Stop).FullName;if($resolved-ne$ExpectedProgram-or(Hash $resolved)-ne$ExpectedProgramSha256){throw 'executable identity mismatch'}
$persistent=View 'PersistentStore';$active=View 'ActiveStore';if($persistent.enabled-ne'True'-or$active.enabled-ne'True'){throw 'rule is not enabled before remediation'}
foreach($v in @($persistent,$active)){if($v.name-ne$authorized-or$v.instance_id-ne$authorized-or$v.program-ne$ExpectedProgram-or$v.action-ne'Allow'-or$v.direction-ne'Inbound'){throw 'rule identity or semantic mismatch'};if($v.remote_address-ne'Any'-or$v.interface_type-ne'Any'){throw 'rule is not proven broadly exposed'}}
$pre=[ordered]@{schema_version='nora.phase2_exact_firewall_remediation_pre_v1';repository_commit=$RepositoryCommit;host_identity=[Security.Principal.WindowsIdentity]::GetCurrent().Name;authorization='disable exact broad metatester inbound allow rule';rule_name=$authorized;executable=[ordered]@{path=$resolved;size=(Get-Item $resolved).Length;sha256=Hash $resolved};persistent=$persistent;active=$active;captured_utc=(Get-Date).ToUniversalTime().ToString('o')};Atomic $PreArtifactPath $pre;$preHash=Hash $PreArtifactPath
Set-NetFirewallRule -PolicyStore PersistentStore -Name $authorized -Enabled False -ErrorAction Stop
$postPersistent=View 'PersistentStore';$postActive=View 'ActiveStore';if($postPersistent.enabled-ne'False'-or$postActive.enabled-ne'False'){throw 'exact rule disable did not become effective'}
$a=($persistent|ConvertTo-Json -Depth 12 -Compress).Replace('"enabled":"True"','"enabled":"False"');$b=$postPersistent|ConvertTo-Json -Depth 12 -Compress;if($a-ne$b){throw 'persistent rule changed beyond enabled state'};$c=($active|ConvertTo-Json -Depth 12 -Compress).Replace('"enabled":"True"','"enabled":"False"');$d=$postActive|ConvertTo-Json -Depth 12 -Compress;if($c-ne$d){throw 'active rule changed beyond enabled state'}
$receipt=[ordered]@{schema_version='nora.phase2_exact_firewall_remediation_receipt_v1';repository_commit=$RepositoryCommit;host_identity=[Security.Principal.WindowsIdentity]::GetCurrent().Name;rule_name=$authorized;policy_store='PersistentStore';operation='disable';pre_artifact_path=[IO.Path]::GetFullPath($PreArtifactPath);pre_artifact_sha256=$preHash;before=$persistent;after=$postPersistent;active_after=$postActive;only_enabled_changed=$true;rule_still_exists=$true;completed_utc=(Get-Date).ToUniversalTime().ToString('o')};Atomic $ReceiptPath $receipt;[ordered]@{verdict='PASS';pre_artifact_sha256=$preHash;receipt_path=[IO.Path]::GetFullPath($ReceiptPath);receipt_sha256=Hash $ReceiptPath}|ConvertTo-Json -Compress
