param([Parameter(Mandatory=$true)][string]$IncomingRoot,[Parameter(Mandatory=$true)][string]$RunId,[ValidateSet('GDAXI','AUDCAD')][string]$Symbol)
$ErrorActionPreference='Stop';$csv='nora_phase2_time_rule_tester_v1.csv';$terminal='C:\Program Files\Darwinex MetaTrader 5\terminal64.exe';$run=Join-Path $env:USERPROFILE ('NoraPhase2TimeRuleValidation\runs\'+$RunId)
function Hash($p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
if(Test-Path $run){throw 'occupied run destination'};New-Item -ItemType Directory $run|Out-Null
try{
 $packet=Get-Content (Join-Path $IncomingRoot 'execution_packet.json') -Raw|ConvertFrom-Json;$batch=Get-Content (Join-Path $IncomingRoot 'final_batch.json') -Raw|ConvertFrom-Json
 if($packet.target_identifier-ne'time_rules'-or$packet.result_filename-ne$csv){throw 'wrong target packet'}
 $ex5=Join-Path $IncomingRoot ('compile\'+$packet.ex5_path);if(!(Test-Path $ex5)-or(Hash $ex5)-ne$packet.ex5_sha256-or(Get-Item $ex5).Length-ne$packet.ex5_size){throw 'packet-bound EX5 mismatch'}
 if(Get-Process terminal64 -ErrorAction SilentlyContinue){throw 'conflicting terminal'}
 $data=Get-ChildItem "$env:APPDATA\MetaQuotes\Terminal" -Directory|?{(Test-Path (Join-Path $_.FullName 'origin.txt'))-and((Get-Content (Join-Path $_.FullName 'origin.txt') -Raw).Trim()-eq'C:\Program Files\Darwinex MetaTrader 5')}|select -First 1 -Expand FullName;if(!$data){throw 'Darwinex data root absent'}
 $expertDir=Join-Path $data 'MQL5\Experts\NoraPhase2TimeRule';New-Item -ItemType Directory -Force $expertDir|Out-Null;$installed=Join-Path $expertDir 'NoraPhase2TimeRuleTesterCanaryV1.ex5';Copy-Item $ex5 $installed -Force;if((Hash $installed)-ne$packet.ex5_sha256){throw 'installed EX5 mismatch'}
 $common=Join-Path (Split-Path $data -Parent) 'Common\Files';$commonCsv=Join-Path $common $csv;if(Test-Path $commonCsv){Remove-Item $commonCsv -Force}
 $journal=Join-Path $data ('Tester\logs\'+(Get-Date -Format yyyyMMdd)+'.log');$before=if(Test-Path $journal){(Get-Item $journal).Length}else{0}
 $ini=Get-Content 'C:\Program Files\Darwinex MetaTrader 5\backtest_run.ini' -Raw;$ini=[regex]::Replace($ini,'(?m)^Expert=.*$','Expert=NoraPhase2TimeRule\NoraPhase2TimeRuleTesterCanaryV1');$ini=[regex]::Replace($ini,'(?m)^Symbol=.*$',('Symbol='+$Symbol));$ini=[regex]::Replace($ini,'(?m)^Period=.*$','Period=M1');$ini=[regex]::Replace($ini,'(?m)^Report=.*$',('Report='+(Join-Path $run 'tester.htm')));$ini=[regex]::Replace($ini,'(?m)^ReplaceReport=.*$','ReplaceReport=1');Set-Content (Join-Path $run 'tester.ini') $ini -Encoding ascii
 $start=(Get-Date).ToUniversalTime();$p=Start-Process $terminal -ArgumentList ('/config:"'+(Join-Path $run 'tester.ini')+'"') -PassThru;if(!$p.WaitForExit(120000)){$p.Kill();throw 'tester timeout'};$end=(Get-Date).ToUniversalTime();if(!(Test-Path $commonCsv)){throw 'missing fresh CSV'};Copy-Item $commonCsv (Join-Path $run $csv)
 $bytes=if(Test-Path $journal){$all=[IO.File]::ReadAllBytes($journal);if($all.Length-lt$before){throw 'journal truncated'};$all[$before..($all.Length-1)]}else{[byte[]]@()};[IO.File]::WriteAllBytes((Join-Path $run 'tester-journal.log'),$bytes)
 $text=[Text.Encoding]::Unicode.GetString($bytes);$complete=$text-match[regex]::Escape($packet.completion_marker);$failure=$text-match[regex]::Escape($packet.failure_marker);@{marker=$packet.completion_marker;present=$complete}|ConvertTo-Json|Set-Content (Join-Path $run 'completion-marker.json') -Encoding utf8;@{marker=$packet.failure_marker;present=$failure}|ConvertTo-Json|Set-Content (Join-Path $run 'failure-marker.json') -Encoding utf8;if(!$complete-or$failure){throw 'marker state'}
 $csvHash=Hash (Join-Path $run $csv);$journalHash=Hash (Join-Path $run 'tester-journal.log');$report=Join-Path $run 'tester.htm';if(Test-Path $report){Move-Item $report (Join-Path $run 'tester-native.htm')};@{schema_version='nora.time_rule_tester_evidence_v1';run_identifier=$RunId;symbol=$Symbol;timeframe='M1';start_utc=$start.ToString('o');completion_utc=$end.ToString('o');ex5_sha256=$packet.ex5_sha256;csv_sha256=$csvHash;journal_sha256=$journalHash;completion_marker_present=$true;failure_marker_present=$false;no_trading_operations=$true;native_report_captured=(Test-Path (Join-Path $run 'tester-native.htm'));substitute='bounded native journal and fixed-vector output'}|ConvertTo-Json -Depth 5|Set-Content $report -Encoding utf8
 Copy-Item (Join-Path $IncomingRoot 'compile\compiler_record.json') (Join-Path $run 'compile.json');Copy-Item (Join-Path $IncomingRoot 'compile\compile.log') (Join-Path $run 'compile.log')
 $record=[ordered]@{schema_version='nora.time_rule_run_record_v1';run_identifier=$RunId;target_identifier='time_rules';host_symbol=$Symbol;timeframe='M1';requested_start_utc=$start.ToString('o');observed_completion_utc=$end.ToString('o');final_batch_identity=$batch.final_batch_identity;compile_input_identity=$packet.compile_input_identity;compiler_output_identity=$packet.compiler_output_identity;execution_packet_identity=$packet.execution_packet_identity;ex5_sha256=$packet.ex5_sha256;runtime_identity=$packet.runtime_identity;tester_identity=$packet.tester_identity;package_identity=$packet.package_identity;rust_plan_identity=$packet.rust_plan_identity;expected_vector_identity=$packet.expected_vector_identity;csv_schema_identity=$packet.csv_schema_identity;clock_contract_identities=$packet.clock_contract_identities;scenario_identities=$packet.scenario_identities;tester_configuration_sha256=Hash (Join-Path $run 'tester.ini');result_csv_sha256=$csvHash;journal_source=$journal;journal_baseline_bytes=$before;journal_segment_sha256=$journalHash;completion_marker_present=$true;failure_marker_present=$false;process_exit=$p.ExitCode;no_trading_operations=$true;collection_state='complete'};$record|ConvertTo-Json -Depth 12|Set-Content (Join-Path $run 'execution.json') -Encoding utf8;Write-Output $run
}catch{Remove-Item $run -Recurse -Force -ErrorAction SilentlyContinue;throw}
