param([Parameter(Mandatory=$true)][string]$IncomingRoot,[Parameter(Mandatory=$true)][string]$RunId,[Parameter(Mandatory=$true)][ValidateSet('GDAXI','AUDCAD')][string]$Symbol)
$ErrorActionPreference='Stop'
$target='phase2_ten_strategy_suite';$csv='nora_phase2_ten_strategy_v1.csv';$terminal='C:\Program Files\Darwinex MetaTrader 5\terminal64.exe';$template='C:\Program Files\Darwinex MetaTrader 5\backtest_run.ini'
function Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLower()}
function ReplaceLine([string]$Text,[string]$Key,[string]$Value){$r='(?m)^'+[regex]::Escape($Key)+'=.*$';if($Text -notmatch $r){throw "missing template key $Key"};[regex]::Replace($Text,$r,$Key+'='+$Value)}
$packet=Get-Content (Join-Path $IncomingRoot 'execution_packet.json') -Raw|ConvertFrom-Json;$batch=Get-Content (Join-Path $IncomingRoot 'final_batch.json') -Raw|ConvertFrom-Json
if($packet.target_identifier-ne$target -or $packet.execution_packet_identity-ne'a2f2982eeff45e6c567d14ad9673f0ce8d9741ed19b60dead1043ba155ea17ec'){throw 'wrong packet'}
if($batch.final_batch_identity-ne'd22f21f876b52e32acbcd6274c491797b7d6df2eabf9820e4145ae828760249c'){throw 'wrong final batch'}
if(!(Test-Path $template)){throw 'missing installed backtest template'}
$ini=Get-Content $template -Raw
foreach($k in @('Environment','Login','Server')){if($ini -notmatch ('(?m)^'+$k+'=.+$')){throw "template lacks configured $k"}}
if(Get-Process terminal64,metatester64 -ErrorAction SilentlyContinue){throw 'conflicting terminal_or_tester'}
$data=Get-ChildItem "$env:APPDATA\MetaQuotes\Terminal" -Directory|?{(Test-Path (Join-Path $_.FullName 'origin.txt')) -and ((Get-Content (Join-Path $_.FullName 'origin.txt') -Raw).Trim() -eq 'C:\Program Files\Darwinex MetaTrader 5')}|select -First 1 -Expand FullName;if(!$data){throw 'Darwinex data root absent'}
$root=Join-Path $env:USERPROFILE 'NoraPhase2TenStrategy\validation\packet-runs';$run=Join-Path $root $RunId;if(Test-Path $run){throw 'existing run'};New-Item -ItemType Directory -Path $run|Out-Null
try{
 $ex5=Join-Path $IncomingRoot ('compile\'+$packet.ex5_path);if(!(Test-Path $ex5) -or (Hash $ex5)-ne$packet.ex5_sha256){throw 'bound ex5 mismatch'}
 $expert=Join-Path $data 'MQL5\Experts\NoraPhase2TenStrategy';New-Item -ItemType Directory -Force $expert|Out-Null;$installed=Join-Path $expert $packet.ex5_path;Copy-Item $ex5 $installed -Force;if((Hash $installed)-ne$packet.ex5_sha256){throw 'installed ex5 mismatch'}
 $common=Join-Path (Split-Path $data -Parent) 'Common\Files';$commonCsv=Join-Path $common $csv;if(Test-Path $commonCsv){Remove-Item $commonCsv -Force}
 $ini=ReplaceLine $ini 'Expert' 'NoraPhase2TenStrategy\NoraPhase2TenStrategyTesterCanaryV1';$ini=ReplaceLine $ini 'Symbol' $Symbol;$ini=ReplaceLine $ini 'Period' 'M1';$ini=ReplaceLine $ini 'Model' '0';$ini=ReplaceLine $ini 'FromDate' '2020.07.01';$ini=ReplaceLine $ini 'ToDate' '2026.07.01';$ini=ReplaceLine $ini 'Report' (Join-Path $run 'tester.htm');$ini=ReplaceLine $ini 'ReplaceReport' '1';$ini=ReplaceLine $ini 'ShutdownTerminal' '1';$ini=ReplaceLine $ini 'UseLocal' '1';$ini=ReplaceLine $ini 'UseRemote' '0';$ini=ReplaceLine $ini 'UseCloud' '0';$ini=ReplaceLine $ini 'Visual' '0';$iniPath=Join-Path $run 'tester.ini';Set-Content $iniPath $ini -Encoding ascii
 $journal=Join-Path $data ('Tester\logs\'+(Get-Date -Format yyyyMMdd)+'.log');$before=if(Test-Path $journal){(Get-Item $journal).Length}else{0};$start=(Get-Date).ToUniversalTime();$arg='/config:"'+$iniPath+'"';$p=Start-Process -FilePath $terminal -ArgumentList $arg -PassThru;if(!$p.WaitForExit(120000)){$p.Kill();throw 'tester timeout'};$end=(Get-Date).ToUniversalTime();if(!(Test-Path $commonCsv)){throw 'missing fresh CSV'};Copy-Item $commonCsv (Join-Path $run $csv)
 $segment='';if(Test-Path $journal){$fs=[IO.File]::OpenRead($journal);$fs.Seek($before,[IO.SeekOrigin]::Begin)|Out-Null;$n=$fs.Length-$before;$b=New-Object byte[] $n;$null=$fs.Read($b,0,$n);$fs.Close();$segment=[Text.Encoding]::Unicode.GetString($b)};$segment|Set-Content (Join-Path $run 'tester-journal.log') -Encoding utf8
 $completion=$segment -match [regex]::Escape($packet.completion_marker);$failure=$segment -match [regex]::Escape($packet.failure_marker);$agentStarted=$segment -match 'testing of Experts\\NoraPhase2TenStrategy';$eaStarted=$segment -match 'NoraPhase2TenStrategyTesterCanaryV1';$fixture=$completion -and (Test-Path (Join-Path $run $csv));if(!$agentStarted -or !$eaStarted -or !$fixture -or !$completion -or $failure){throw 'launch_or_completion_contract'}
 @{run_identifier=$RunId;target_identifier=$target;host_symbol=$Symbol;timeframe='M1';terminal_path=$terminal;terminal_argument=$arg;terminal_data_directory=$data;tester_agent_started=$agentStarted;ea_started=$eaStarted;fixture_consumed=$fixture;completion_marker_present=$completion;failure_marker_present=$failure;result_csv_sha256=Hash (Join-Path $run $csv);ini_sha256=Hash $iniPath;process_exit=$p.ExitCode;requested_start_utc=$start.ToString('o');observed_completion_utc=$end.ToString('o');execution_packet_identity=$packet.execution_packet_identity;final_batch_identity=$batch.final_batch_identity;ex5_sha256=$packet.ex5_sha256;collection_state='complete'}|ConvertTo-Json -Depth 5|Set-Content (Join-Path $run 'execution.json') -Encoding utf8;Write-Output $run
}catch{@{run_identifier=$RunId;target_identifier=$target;collection_state='failed';failure=$_.Exception.Message}|ConvertTo-Json|Set-Content (Join-Path $run 'execution.json') -Encoding utf8;throw}
