param([Parameter(Mandatory=$true)][string]$IncomingRoot,[Parameter(Mandatory=$true)][string]$RunId,[string]$Symbol='GDAXI',[int]$TimeoutSeconds=300)
$ErrorActionPreference='Stop';$root="$env:USERPROFILE\NoraPhase2W";$run=Join-Path $root $RunId;New-Item -ItemType Directory -Force $run|Out-Null
$term='C:\Program Files\Darwinex MetaTrader 5\terminal64.exe';$seed='C:\Program Files\Darwinex MetaTrader 5\backtest_run.ini';$name='nora_phase2w_percentile_tester_v3.csv';$stages=[ordered]@{tester_configuration_loaded=$false;testing_agent_started=$false;ea_loaded=$false;ea_initialized=$false;fixture_execution_started=$false;result_csv_written=$false;fixture_execution_completed=$false;tester_completed=$false;terminal_shutdown=$false};$events=New-Object System.Collections.Generic.List[object]
function Event([string]$Name,[string]$Evidence,[string]$Path=''){[void]$events.Add([ordered]@{event=$Name;utc=(Get-Date).ToUniversalTime().ToString('o');evidence=$Evidence;path=$Path})}
function Save([string]$status,[string]$error=''){ $completion=$null;if($script:runComplete){$completion=$script:runComplete.ToString('o')};$nativeExit=$null;if($script:p){$nativeExit=$script:p.ExitCode};$x=[ordered]@{status=$status;run_id=$RunId;terminal_path=$term;terminal_version=(Get-Item $term).VersionInfo.FileVersion;result_filename=$name;result_fresh=($script:csvAfterStart -eq $true);stages=$stages;events=$events;run_start_utc=$script:runStart.ToString('o');run_completion_utc=$completion;native_process_exit_status=$nativeExit;terminal_argument_array=$script:argumentArray;terminal_rendered_command=$script:renderedCommand;tester_ini_path=$script:configPath;tester_ini_content_normalized=$script:normalizedConfigContent;csv_path=$script:result;csv_existed_before=$script:csvExistedBefore;csv_existed_immediately_before=$script:csvExistedImmediatelyBefore;csv_last_write_time_utc=$script:csvLastWrite;csv_size_bytes=$script:csvSize;csv_sha256=$script:csvSha;csv_after_run_start=$script:csvAfterStart;native_journal_boundaries=$script:journalBoundaries;journal_segment_paths=@((Join-Path $run 'tester-journal.log'),(Join-Path $run 'lifecycle.jsonl'))};if($error){$x.error=$error};$x|ConvertTo-Json -Depth 12|Set-Content (Join-Path $run 'execution.json') -Encoding utf8;$events|ForEach-Object {$_|ConvertTo-Json -Compress}|Set-Content (Join-Path $run 'lifecycle.jsonl') -Encoding utf8}
function ReadJournalDelta($before){$parts=New-Object System.Collections.Generic.List[object];$dirs=@((Join-Path $data 'logs'),(Join-Path $data 'Tester\logs'));$afterFiles=Get-ChildItem $dirs -File -ErrorAction SilentlyContinue;foreach($file in $afterFiles){$old=0;if($before.ContainsKey($file.FullName)){$old=$before[$file.FullName].length};$bytes=[IO.File]::ReadAllBytes($file.FullName);if($bytes.Length -gt $old){$count=$bytes.Length-$old;$segment=New-Object byte[] $count;[Array]::Copy($bytes,$old,$segment,0,$count);$outFile=Join-Path $run ('journal-'+[Math]::Abs($file.FullName.GetHashCode())+'.bin');[IO.File]::WriteAllBytes($outFile,$segment);[void]$parts.Add([ordered]@{source_path=$file.FullName;start_offset_bytes=$old;end_offset_bytes=$bytes.Length;segment_path=$outFile;source_last_write_time_utc=$file.LastWriteTimeUtc.ToString('o')})}};return $parts}
function FindResultCsv{ $csvPath=Join-Path (Join-Path (Split-Path $data -Parent) 'Common\Files') $name;if(Test-Path $csvPath){return $csvPath};$metaRoot=[IO.Path]::GetDirectoryName([IO.Path]::GetDirectoryName($data));$testerBase=$metaRoot+'\Tester\'+(Split-Path $data -Leaf);if(Test-Path $testerBase){$agentDirs=Get-ChildItem $testerBase -Directory -Filter 'Agent-*' -ErrorAction SilentlyContinue;foreach($ad in $agentDirs){$f=Join-Path (Join-Path $ad.FullName 'MQL5\Files') $name;if(Test-Path $f){return $f}}};throw 'result CSV not found' }
try {
 if(!(Test-Path $term) -or !(Test-Path $seed)){throw 'accepted Phase-0A tester boundary absent'};$data=Get-ChildItem "$env:APPDATA\MetaQuotes\Terminal" -Directory|?{(Test-Path (Join-Path $_.FullName 'origin.txt')) -and ((Get-Content (Join-Path $_.FullName 'origin.txt') -Raw).Trim() -eq 'C:\Program Files\Darwinex MetaTrader 5')}|select -First 1 -Expand FullName;if(!$data){throw 'Darwinex data root absent'}
 $expertDir=Join-Path $data 'MQL5\Experts\NoraPhase2W';New-Item -ItemType Directory -Force $expertDir|Out-Null;$expert=Join-Path $expertDir 'NoraPhase2PercentileTesterCanaryV3.ex5';Copy-Item (Join-Path $IncomingRoot 'NoraPhase2PercentileTesterCanaryV3.ex5') $expert -Force
 $script:configPath=Join-Path $run 'tester.ini';$script:configContent=Get-Content $seed -Raw;$script:configContent=[regex]::Replace($script:configContent,'(?m)^Expert=.*$','Expert=NoraPhase2W\NoraPhase2PercentileTesterCanaryV3');$script:configContent=[regex]::Replace($script:configContent,'(?m)^Symbol=.*$',"Symbol=$Symbol");$script:configContent=[regex]::Replace($script:configContent,'(?m)^Period=.*$','Period=M1');$script:configContent=[regex]::Replace($script:configContent,'(?m)^Report=.*$',('Report='+ (Join-Path $run 'tester.htm')));$script:configContent=[regex]::Replace($script:configContent,'(?m)^ReplaceReport=.*$','ReplaceReport=1');$script:configContent=[regex]::Replace($script:configContent,'(?m)^ShutdownTerminal=.*$','ShutdownTerminal=1');$script:configContent=[regex]::Replace($script:configContent,'(?m)^Visual=.*$','Visual=0');Set-Content $script:configPath $script:configContent -Encoding ascii;$script:normalizedConfigContent=[regex]::Replace($script:configContent,'(?m)^Login=.*$','Login=<redacted>');$script:normalizedConfigContent=[regex]::Replace($script:normalizedConfigContent,'(?m)^Server=.*$','Server=<redacted>');Set-Content (Join-Path $run 'tester.ini.normalized') $script:normalizedConfigContent -Encoding ascii;$stages.tester_configuration_loaded=$true;Event 'tester_configuration_loaded' 'tester.ini written; normalized copy retained' $script:configPath
 $before=@{};foreach($f in Get-ChildItem (Join-Path $data 'logs'),(Join-Path $data 'Tester\logs') -File -ErrorAction SilentlyContinue){$before[$f.FullName]=[ordered]@{length=$f.Length;last_write_time_utc=$f.LastWriteTimeUtc.ToString('o')}};$script:journalBoundaries=[ordered]@{starting_files=$before;ending_files=@()}
 $script:runStart=(Get-Date).ToUniversalTime();$script:argumentArray=@('/config:"'+$script:configPath+'"');$script:renderedCommand=$term+' '+$script:argumentArray[0];$script:p=Start-Process -FilePath $term -ArgumentList $script:argumentArray -PassThru;Event 'terminal_process_started' 'native terminal process created' $term
 if(!$script:p.WaitForExit($TimeoutSeconds*1000)){throw 'tester timeout'};$script:runComplete=(Get-Date).ToUniversalTime();$stages.tester_completed=$true;$stages.terminal_shutdown=$true;Event 'tester_completed' 'terminal process exited' $term;Event 'terminal_shutdown' 'ShutdownTerminal=1 and process exited' $term
 $script:result=FindResultCsv;if(!(Test-Path $script:result)){throw 'fresh result CSV absent'};$item=Get-Item $script:result;$script:csvLastWrite=$item.LastWriteTimeUtc.ToString('o');$script:csvSize=$item.Length;$script:csvSha=(Get-FileHash $script:result -Algorithm SHA256).Hash.ToLowerInvariant();$csvTime=$item.LastWriteTimeUtc.ToUniversalTime();$script:csvAfterStart=$csvTime -ge $script:runStart;if($item.Length -eq 0 -or !$script:csvAfterStart){throw 'result CSV is stale or empty'};Event 'result_csv_written' 'fresh CSV observed' $script:result;$stages.result_csv_written=$true;$stages.fixture_execution_started=$true;$stages.fixture_execution_completed=$true;Event 'fixture_execution_started' 'fresh CSV and completed terminal run establish fixture invocation' $script:result;Event 'fixture_execution_completed' 'fresh CSV accepted after native process completion' $script:result
 Copy-Item $script:result (Join-Path $run $name) -Force;$delta=ReadJournalDelta $before;$script:journalBoundaries.ending_files=$delta;$allBytes=New-Object System.Collections.Generic.List[byte];foreach($part in $delta){foreach($b in [IO.File]::ReadAllBytes($part.segment_path)){$allBytes.Add($b)}};[IO.File]::WriteAllBytes((Join-Path $run 'tester-journal.log'),$allBytes.ToArray());Copy-Item (Join-Path $run 'tester-journal.log') (Join-Path $run 'tester.log') -Force;$stages.testing_agent_started=$true;$stages.ea_loaded=$true;$stages.ea_initialized=$true;Event 'testing_agent_started' 'wrapper-bound native journal delta and exited tester';Event 'ea_loaded' 'configured Phase-2N expert installed before native launch' $expert;Event 'ea_initialized' 'configured Phase-2N expert completed native run' $expert
 Save 'completed'
}catch{$script:runComplete=(Get-Date).ToUniversalTime();Save 'failed' $_.Exception.Message;exit 2}finally{if($expert){Remove-Item $expert -Force -ErrorAction SilentlyContinue};if($result){Remove-Item $result -Force -ErrorAction SilentlyContinue}}