param([Parameter(Mandatory=$true)][string]$IncomingRoot,[Parameter(Mandatory=$true)][string]$RunId,[Parameter(Mandatory=$true)][ValidateSet('GDAXI','AUDCAD')][string]$Symbol,[Parameter(Mandatory=$true)][long]$BeforeBarCount,[Parameter(Mandatory=$true)][long]$AfterBarCount,[Parameter(Mandatory=$true)][string]$BeforeEarliest,[Parameter(Mandatory=$true)][string]$BeforeLatest,[Parameter(Mandatory=$true)][string]$AfterEarliest,[Parameter(Mandatory=$true)][string]$AfterLatest,[Parameter(Mandatory=$true)][string]$RunDirectory,[Parameter(Mandatory=$true)][string]$EvidenceRoot)
$ErrorActionPreference='Stop'
$target='phase2_ten_strategy_suite';$csv='nora_phase2_ten_strategy_v1.csv';$terminal='C:\Program Files\Darwinex MetaTrader 5\terminal64.exe';$template='C:\Program Files\Darwinex MetaTrader 5\backtest_run.ini'
function Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLower()}
$packet=Get-Content (Join-Path $IncomingRoot 'execution_packet.json') -Raw|ConvertFrom-Json;$batch=Get-Content (Join-Path $IncomingRoot 'final_batch.json') -Raw|ConvertFrom-Json
if($packet.target_identifier-ne$target -or $batch.target_identifier-ne$target -or $batch.execution_packet_identity-ne$packet.execution_packet_identity){throw 'wrong packet'}
if(!(Test-Path $template)){throw 'missing installed backtest template'}
$ini=Get-Content $template -Raw
foreach($k in @('Environment','Login','Server')){if($ini -notmatch ('(?m)^'+$k+'=.+$')){throw "template lacks configured $k"}}
if(Get-Process terminal64,metatester64 -ErrorAction SilentlyContinue){throw 'conflicting terminal_or_tester'}
$data=Get-ChildItem "$env:APPDATA\MetaQuotes\Terminal" -Directory|?{(Test-Path (Join-Path $_.FullName 'origin.txt')) -and ((Get-Content (Join-Path $_.FullName 'origin.txt') -Raw).Trim() -eq 'C:\Program Files\Darwinex MetaTrader 5')}|select -First 1 -Expand FullName;if(!$data){throw 'Darwinex data root absent'}
$root=$EvidenceRoot;$run=$RunDirectory;if(!(Test-Path -LiteralPath $run -PathType Container)){throw 'missing durable prepared run directory'}
try{
 $ex5=Join-Path $IncomingRoot ('compile\'+$packet.ex5_path);if(!(Test-Path $ex5) -or (Hash $ex5)-ne$packet.ex5_sha256){throw 'bound ex5 mismatch'}
 $expert=Join-Path $data 'MQL5\Experts\NoraPhase2TenStrategy';New-Item -ItemType Directory -Force $expert|Out-Null;$installed=Join-Path $expert $packet.ex5_path;Copy-Item $ex5 $installed -Force;if((Hash $installed)-ne$packet.ex5_sha256){throw 'installed ex5 mismatch'}
 $common=Join-Path (Split-Path $data -Parent) 'Common\Files';$commonCsv=Join-Path $common $csv;if(Test-Path $commonCsv){Remove-Item $commonCsv -Force}
 $iniPath=Join-Path $run 'tester.ini';$configBuilder=Join-Path $IncomingRoot 'phase-0a-h\windows\build-ten-strategy-tester-config.ps1';if(!(Test-Path $configBuilder)){throw 'missing bound tester configuration builder'}
 & $configBuilder -Template $template -Destination $iniPath -Symbol $Symbol -Report (Join-Path $run 'tester.htm')
 $collector=Join-Path $IncomingRoot 'phase-0a-h\windows\collect-ten-strategy-environment.ps1';$resolver=Join-Path $IncomingRoot 'phase-0a-h\windows\resolve-phase2-mt5-server-scope.ps1';if(!(Test-Path $collector) -or !(Test-Path $resolver)){throw 'missing bound server-scoped environmental collector'}; & $collector -Phase before -TerminalDataDirectory $data -TerminalPath $terminal -ConfigurationPath $iniPath -Symbol $Symbol -ResolverPath $resolver -Destination (Join-Path $run 'environment-before.json') -ObservedBarCount $BeforeBarCount -EarliestHistoryTimestamp $BeforeEarliest -LatestHistoryTimestamp $BeforeLatest
 $journal=Join-Path $data ('Tester\logs\'+(Get-Date -Format yyyyMMdd)+'.log');$terminalJournal=Join-Path $data ('logs\'+(Get-Date -Format yyyyMMdd)+'.log');$before=if(Test-Path $journal){(Get-Item $journal).Length}else{0};$terminalBefore=if(Test-Path $terminalJournal){(Get-Item $terminalJournal).Length}else{0};$start=(Get-Date).ToUniversalTime();$arg='/config:"'+$iniPath+'"';$p=Start-Process -FilePath $terminal -ArgumentList $arg -PassThru;if(!$p.WaitForExit(120000)){$p.Kill();throw 'tester timeout'};$end=(Get-Date).ToUniversalTime();if(!(Test-Path $commonCsv)){throw 'missing fresh CSV'};Copy-Item $commonCsv (Join-Path $run $csv)
 $segment='';if(Test-Path $journal){$fs=[IO.File]::OpenRead($journal);$fs.Seek($before,[IO.SeekOrigin]::Begin)|Out-Null;$n=$fs.Length-$before;$b=New-Object byte[] $n;$null=$fs.Read($b,0,$n);$fs.Close();$segment=[Text.Encoding]::Unicode.GetString($b)};$segment|Set-Content (Join-Path $run 'tester-journal.log') -Encoding utf8
 $terminalSegment='';if(Test-Path $terminalJournal){$fs=[IO.File]::OpenRead($terminalJournal);$fs.Seek($terminalBefore,[IO.SeekOrigin]::Begin)|Out-Null;$n=$fs.Length-$terminalBefore;$b=New-Object byte[] $n;$null=$fs.Read($b,0,$n);$fs.Close();$terminalSegment=[Text.Encoding]::Unicode.GetString($b)};$terminalSegment|Set-Content (Join-Path $run 'terminal-journal.log') -Encoding utf8
 & $collector -Phase after -TerminalDataDirectory $data -TerminalPath $terminal -ConfigurationPath $iniPath -Symbol $Symbol -ResolverPath $resolver -Destination (Join-Path $run 'environment-after.json') -ObservedBarCount $AfterBarCount -EarliestHistoryTimestamp $AfterEarliest -LatestHistoryTimestamp $AfterLatest
 # Journal wording alone cannot decide acceptance.  A later fail-closed Python
 # contract binds this preserved segment to inventories, bar bounds, payload,
 # and classified cache deltas.  Only an explicit bar/tick payload is rejected
 # here as independently fatal.
 $segLow=$segment.ToLower();$pricePayload=($segLow -match '\b(downloaded|received|loaded)\s+\d+\s+(bar|bars|tick|ticks)\b') -or ($segLow -match '\b(bar|bars|tick|ticks)\s+(downloaded|received)\b');if($pricePayload){@{run_identifier=$RunId;target_identifier=$target;collection_state='failed';failure='price_data_payload_detected';price_data_payload_detected=$true}|ConvertTo-Json -Depth 5|Set-Content (Join-Path $run 'execution.json') -Encoding utf8;throw 'price_data_payload_detected'}
 $completion=$segment -match [regex]::Escape($packet.completion_marker);$failure=$segment -match [regex]::Escape($packet.failure_marker);$agentStarted=$segment -match 'testing of Experts\\NoraPhase2TenStrategy';$eaStarted=$segment -match 'NoraPhase2TenStrategyTesterCanaryV1';$fixture=$completion -and (Test-Path (Join-Path $run $csv));if(!$agentStarted -or !$eaStarted -or !$fixture -or !$completion -or $failure){throw 'launch_or_completion_contract'}
 @{marker=$packet.completion_marker;present=$completion}|ConvertTo-Json|Set-Content (Join-Path $run 'completion-marker.json') -Encoding utf8;@{marker=$packet.failure_marker;present=$failure}|ConvertTo-Json|Set-Content (Join-Path $run 'failure-marker.json') -Encoding utf8
 @{run_identifier=$RunId;target_identifier=$target;host_symbol=$Symbol;timeframe='M1';terminal_path=$terminal;terminal_argument=$arg;terminal_data_directory=$data;tester_agent_started=$agentStarted;ea_started=$eaStarted;fixture_consumed=$fixture;completion_marker_present=$completion;failure_marker_present=$failure;result_csv_sha256=Hash (Join-Path $run $csv);ini_sha256=Hash $iniPath;process_exit=$p.ExitCode;requested_start_utc=$start.ToString('o');observed_completion_utc=$end.ToString('o');execution_packet_identity=$packet.execution_packet_identity;final_batch_identity=$batch.final_batch_identity;ex5_sha256=$packet.ex5_sha256;price_data_payload_detected=$false;environmental_acceptance='pending_complete_forensic_contract';collection_state='complete'}|ConvertTo-Json -Depth 5|Set-Content (Join-Path $run 'execution.json') -Encoding utf8;$complete=$run -replace '\\.running$','.complete';if($complete -eq $run -or (Test-Path -LiteralPath $complete)){throw 'invalid durable completion path'};Move-Item -LiteralPath $run -Destination $complete;Write-Output $complete
}catch{@{run_identifier=$RunId;target_identifier=$target;collection_state='failed';failure=$_.Exception.Message}|ConvertTo-Json|Set-Content (Join-Path $run 'execution.json') -Encoding utf8;throw}
