param(
 [Parameter(Mandatory=$true)][string]$IncomingRoot,
 [Parameter(Mandatory=$true)][string]$RunId,
 [Parameter(Mandatory=$true)][ValidateSet('GDAXI','AUDCAD')][string]$Symbol,
 [Parameter(Mandatory=$true)][string]$RunDirectory,
 [Parameter(Mandatory=$true)][string]$EvidenceRoot
)
$ErrorActionPreference='Stop'
$terminal='C:\Program Files\Darwinex MetaTrader 5\terminal64.exe';$template='C:\Program Files\Darwinex MetaTrader 5\backtest_run.ini';$start='2020.07.01';$finish='2026.07.01';$output='nora_phase2_offline_cache_probe.json';$containment=Join-Path $IncomingRoot 'phase-0a-h\windows\phase2-network-containment.ps1';$inventory=Join-Path $IncomingRoot 'phase-0a-h\windows\phase2-cache-inventory.ps1';$resolver=Join-Path $IncomingRoot 'phase-0a-h\windows\resolve-phase2-mt5-server-scope.ps1';$compiler=Join-Path $IncomingRoot 'phase-0a-h\windows\compile-phase2-offline-cache-probe.ps1';$source=Join-Path $IncomingRoot 'phase-0a-h\windows\NoraPhase2OfflineCacheProbeV1.mq5'
function Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()}
function Json([string]$Path){Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json}
function AtomicJson([string]$Path,$Value){$tmp=$Path+'.partial.'+[guid]::NewGuid().ToString('N');$Value|ConvertTo-Json -Depth 16 -Compress|Set-Content -LiteralPath $tmp -Encoding utf8 -NoNewline;Move-Item -LiteralPath $tmp -Destination $Path}
function Connections(){@(Get-Process terminal64,metatester64 -ErrorAction SilentlyContinue|ForEach-Object{$p=$_;Get-NetTCPConnection -OwningProcess $p.Id -ErrorAction SilentlyContinue|Where-Object{$_.RemoteAddress -notin @('127.0.0.1','::1','0.0.0.0','::')}|ForEach-Object{[ordered]@{pid=$p.Id;process=$p.ProcessName;remote_address=$_.RemoteAddress;remote_port=$_.RemotePort;state=[string]$_.State}}})}
function CompareCache($Before,$After){$left=@{};$right=@{};foreach($x in @($Before.objects)){$left[$x.relative_path]=$x};foreach($x in @($After.objects)){$right[$x.relative_path]=$x};$added=@($right.Keys|Where-Object{!$left.ContainsKey($_)});$missing=@($left.Keys|Where-Object{!$right.ContainsKey($_)});$changed=@($left.Keys|Where-Object{$right.ContainsKey($_) -and (($left[$_]|ConvertTo-Json -Depth 24 -Compress)-ne($right[$_]|ConvertTo-Json -Depth 24 -Compress))});$renamed=@();foreach($a in $added){$candidate=@($missing|Where-Object{$right[$a].sha256 -and $right[$a].sha256-eq$left[$_].sha256});foreach($m in $candidate){$renamed+=[ordered]@{from=$m;to=$a;sha256=$right[$a].sha256}}};$scopeMatch=($Before.server_scope.server_binding_identity-eq$After.server_scope.server_binding_identity);$configMatch=($Before.server_scope.configuration_sha256-eq$After.server_scope.configuration_sha256);[ordered]@{added=$added;missing=$missing;changed=$changed;renamed=$renamed;server_scope_unchanged=$scopeMatch;configuration_unchanged=$configMatch;before_inventory_identity=$Before.inventory_identity;after_inventory_identity=$After.inventory_identity;accepted=(($added.Count-eq 0)-and($missing.Count-eq 0)-and($changed.Count-eq 0)-and($renamed.Count-eq 0)-and$scopeMatch-and$configMatch);policy='strict_no_history_mutation_subset_of_nora.history_sync_marker_classification_v2'} }
if(@($containment,$inventory,$resolver,$compiler,$source|Where-Object{!(Test-Path -LiteralPath $_)}).Count){throw 'missing bound cache preflight role'}
if(Get-Process terminal64,metatester64 -ErrorAction SilentlyContinue){throw 'conflicting terminal_or_tester'}
& $containment -Action status -CampaignId $RunId -EvidenceRoot $EvidenceRoot|Out-Null
$matches=@(Get-ChildItem "$env:APPDATA\MetaQuotes\Terminal" -Directory|Where-Object{(Test-Path (Join-Path $_.FullName 'origin.txt')) -and ((Get-Content (Join-Path $_.FullName 'origin.txt') -Raw).Trim() -eq 'C:\Program Files\Darwinex MetaTrader 5')});if($matches.Count-ne 1){throw 'ambiguous or missing Darwinex terminal data root'};$data=$matches[0].FullName;$ini=Get-Content -LiteralPath $template -Raw;foreach($pair in @(@('Expert','NoraPhase2OfflineCacheProbe\NoraPhase2OfflineCacheProbeV1'),@('Symbol',$Symbol),@('Period','M1'),@('Model','0'),@('FromDate',$start),@('ToDate',$finish),@('Report',(Join-Path $RunDirectory 'probe-tester.htm')),@('ReplaceReport','1'),@('ShutdownTerminal','1'),@('UseLocal','1'),@('UseRemote','0'),@('UseCloud','0'),@('Visual','0'))){$pattern='(?m)^'+[regex]::Escape($pair[0])+'=.*$';if($ini-notmatch$pattern){throw 'missing tester configuration key'};$ini=[regex]::Replace($ini,$pattern,$pair[0]+'='+$pair[1])};$iniPath=Join-Path $RunDirectory 'probe-tester.ini';Set-Content -LiteralPath $iniPath -Value $ini -Encoding ascii;$beforePath=Join-Path $RunDirectory 'cache-before.json';& $inventory -TerminalDataDirectory $data -TerminalPath $terminal -ConfigurationPath $iniPath -Symbols @($Symbol) -ResolverPath $resolver -Destination $beforePath|Out-Null;$before=Json $beforePath;if($before.empty_relevant_inventory -or $before.relevant_file_count -eq 0){throw 'empty relevant server-scoped cache inventory'}
try{
 $compile=Join-Path $RunDirectory 'probe-compile';& $compiler -Source $source -Destination $compile|Out-Null;$compilerRecord=Json (Join-Path $compile 'compiler-record.json');$expertDir=Join-Path $data 'MQL5\Experts\NoraPhase2OfflineCacheProbe';New-Item -ItemType Directory -Path $expertDir -Force|Out-Null;$expert=Join-Path $expertDir 'NoraPhase2OfflineCacheProbeV1.ex5';Copy-Item -LiteralPath (Join-Path $compile 'NoraPhase2OfflineCacheProbeV1.ex5') -Destination $expert -Force;if((Hash $expert)-ne$compilerRecord.ex5_sha256){throw 'probe EX5 binding'}
 $common=Join-Path (Split-Path $data -Parent) 'Common\Files';$commonOutput=Join-Path $common $output;if(Test-Path -LiteralPath $commonOutput){Remove-Item -LiteralPath $commonOutput -Force};$ini=Get-Content -LiteralPath $template -Raw;foreach($pair in @(@('Expert','NoraPhase2OfflineCacheProbe\NoraPhase2OfflineCacheProbeV1'),@('Symbol',$Symbol),@('Period','M1'),@('Model','0'),@('FromDate',$start),@('ToDate',$finish),@('Report',(Join-Path $RunDirectory 'probe-tester.htm')),@('ReplaceReport','1'),@('ShutdownTerminal','1'),@('UseLocal','1'),@('UseRemote','0'),@('UseCloud','0'),@('Visual','0'))){$pattern='(?m)^'+[regex]::Escape($pair[0])+'=.*$';if($ini-notmatch$pattern){throw 'missing tester configuration key'};$ini=[regex]::Replace($ini,$pattern,$pair[0]+'='+$pair[1])};$iniPath=Join-Path $RunDirectory 'probe-tester.ini';Set-Content -LiteralPath $iniPath -Value $ini -Encoding ascii
 $testerLog=Join-Path $data ('Tester\logs\'+(Get-Date -Format yyyyMMdd)+'.log');$terminalLog=Join-Path $data ('logs\'+(Get-Date -Format yyyyMMdd)+'.log');$testerBefore=if(Test-Path $testerLog){(Get-Item $testerLog).Length}else{0};$terminalBefore=if(Test-Path $terminalLog){(Get-Item $terminalLog).Length}else{0};$network=@();$process=Start-Process -FilePath $terminal -ArgumentList ('/config:"'+$iniPath+'"') -PassThru;$deadline=(Get-Date).ToUniversalTime().AddSeconds(180);while(!$process.HasExited){$network+=@(Connections);if((Get-Date).ToUniversalTime() -ge $deadline){try{$process.Kill()}catch{};throw 'cache_probe_timeout'};Start-Sleep -Milliseconds 500};$network+=@(Connections);if(!(Test-Path -LiteralPath $commonOutput)){throw 'cache probe output absent'};Copy-Item -LiteralPath $commonOutput -Destination (Join-Path $RunDirectory $output);$probe=Json (Join-Path $RunDirectory $output)
 foreach($part in @(@($testerLog,$testerBefore,'tester-journal.log'),@($terminalLog,$terminalBefore,'terminal-journal.log'))){$text='';if(Test-Path $part[0]){$stream=[IO.File]::OpenRead($part[0]);$stream.Seek($part[1],[IO.SeekOrigin]::Begin)|Out-Null;$bytes=New-Object byte[] ($stream.Length-$part[1]);$null=$stream.Read($bytes,0,$bytes.Length);$stream.Close();$text=[Text.Encoding]::Unicode.GetString($bytes)};Set-Content -LiteralPath (Join-Path $RunDirectory $part[2]) -Value $text -Encoding utf8}
 $afterPath=Join-Path $RunDirectory 'cache-after.json';& $inventory -TerminalDataDirectory $data -TerminalPath $terminal -ConfigurationPath $iniPath -Symbols @($Symbol) -ResolverPath $resolver -Destination $afterPath|Out-Null;$after=Json $afterPath;$comparison=CompareCache $before $after;$journals=(Get-Content (Join-Path $RunDirectory 'tester-journal.log') -Raw)+(Get-Content (Join-Path $RunDirectory 'terminal-journal.log') -Raw);$attempt=($journals -match '(?i)history data to synchronize|symbol to be synchronized|synchroniz');$success=@($network|Where-Object{$_.state -eq 'Established'}).Count -gt 0;$coverage=($probe.symbol-eq$Symbol -and $probe.timeframe-eq'M1' -and $probe.returned_requested_interval_bars -gt 0 -and !$probe.duplicate_timestamps -and !$probe.nonmonotonic_timestamps -and $probe.first_returned_timestamp -le '2020.07.01 00:00:00' -and $probe.last_returned_timestamp -ge '2026.07.01 00:00:00')
 $result=[ordered]@{schema_version='nora.phase2_offline_cache_preflight_v2';run_identifier=$RunId;symbol=$Symbol;timeframe='M1';tester_model='0';requested_start=$start;requested_end=$finish;terminal_path=$terminal;terminal_sha256=Hash $terminal;terminal_version=(Get-Item $terminal).VersionInfo.FileVersion;data_root=$data;server_scope=$after.server_scope;configuration_sha256=Hash $iniPath;compiler=$compilerRecord;probe=$probe;cache_comparison=$comparison;network=[ordered]@{successful_connection_observed=$success;blocked_attempt_observed=$attempt;no_attempt_observed=(!$attempt -and !$success);observations=$network};accepted=($coverage -and $comparison.accepted -and !$success);completed_utc=(Get-Date).ToUniversalTime().ToString('o')};AtomicJson (Join-Path $RunDirectory 'offline-cache-preflight.json') $result;if(!$result.accepted){throw 'offline cache preflight rejected'};$complete=$RunDirectory -replace '\.running$','.complete';if($complete-eq$RunDirectory -or(Test-Path -LiteralPath $complete)){throw 'invalid durable completion path'};Move-Item -LiteralPath $RunDirectory -Destination $complete;Write-Output $complete
}catch{$failure=[ordered]@{schema_version='nora.phase2_offline_cache_preflight_v1';run_identifier=$RunId;failure=$_.Exception.Message;failed_utc=(Get-Date).ToUniversalTime().ToString('o')};AtomicJson (Join-Path $RunDirectory 'offline-cache-preflight-failure.json') $failure;throw}
