[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$LaunchId,[Parameter(Mandatory=$true)][string]$CampaignId,
 [Parameter(Mandatory=$true)][string]$CampaignToolPath,[Parameter(Mandatory=$true)][string]$CampaignToolSha256,
 [Parameter(Mandatory=$true)][string]$RepositoryCommit,[Parameter(Mandatory=$true)][string]$CaptureToolPath,[Parameter(Mandatory=$true)][string]$CaptureToolSha256,
 [Parameter(Mandatory=$true)][string]$RunnerPath,[Parameter(Mandatory=$true)][string]$RunnerSha256,[string]$EvidenceRoot='C:\NoraEvidence\Phase2',[int]$CaptureCount=20)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
function Hash($p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Atomic($p,$v){$t=$p+'.partial.'+[guid]::NewGuid().ToString('N');[IO.File]::WriteAllText($t,($v|ConvertTo-Json -Depth 20 -Compress),[Text.UTF8Encoding]::new($false));if(Test-Path $p){throw 'immutable launch artifact exists'};[IO.File]::Move($t,$p)}
foreach($id in @($LaunchId,$CampaignId)){if($id-notmatch'^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$'){throw 'invalid launch or campaign id'}}
if((Hash $CampaignToolPath)-ne$CampaignToolSha256 -or (Hash $CaptureToolPath)-ne$CaptureToolSha256 -or (Hash $RunnerPath)-ne$RunnerSha256){throw 'deployed identity mismatch'}
$root=Join-Path (Join-Path $EvidenceRoot 'firewall-launches') $LaunchId;if(Test-Path $root){throw 'duplicate launch id'};if(Test-Path (Join-Path (Join-Path $EvidenceRoot 'firewall-campaigns') $CampaignId)){throw 'duplicate campaign id'};New-Item -ItemType Directory -Path $root -ErrorAction Stop|Out-Null
$out=Join-Path $root 'stdout.txt';$err=Join-Path $root 'stderr.txt';$cmd=@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$CampaignToolPath,'-Mode','run','-LaunchId',$LaunchId,'-CampaignId',$CampaignId,'-RepositoryCommit',$RepositoryCommit,'-CaptureToolPath',$CaptureToolPath,'-CaptureToolSha256',$CaptureToolSha256,'-RunnerPath',$RunnerPath,'-RunnerSha256',$RunnerSha256,'-EvidenceRoot',$EvidenceRoot,'-CaptureCount',[string]$CaptureCount)
$intent=[ordered]@{schema_version='nora.phase2_firewall_campaign_launch_v1';launch_id=$LaunchId;campaign_id=$CampaignId;user=[Security.Principal.WindowsIdentity]::GetCurrent().Name;campaign_tool_path=$CampaignToolPath;campaign_tool_sha256=$CampaignToolSha256;arguments=$cmd;command_sha256=([BitConverter]::ToString([Security.Cryptography.SHA256]::Create().ComputeHash([Text.Encoding]::UTF8.GetBytes(($cmd|ConvertTo-Json -Compress)))).Replace('-','').ToLowerInvariant();repository_commit=$RepositoryCommit;stdout_path=$out;stderr_path=$err;requested_utc=(Get-Date).ToUniversalTime().ToString('o')};Atomic (Join-Path $root 'intent.json') $intent
$command='powershell.exe '+(($cmd|ForEach-Object{'"'+($_ -replace '"','\\"')+'"'}) -join ' ');$created=Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{CommandLine=$command};if($created.ReturnValue-ne0){Atomic (Join-Path $root 'failure.json') ([ordered]@{launch_id=$LaunchId;reason='process_creation_failure';return_value=$created.ReturnValue});throw 'process creation failure'}
$view=$null;for($i=0;$i-lt100;$i++){Start-Sleep -Milliseconds 100;$owner=Join-Path (Join-Path (Join-Path $EvidenceRoot 'firewall-campaigns') $CampaignId) 'owner.json';if(Test-Path $owner){$o=Get-Content $owner -Raw|ConvertFrom-Json;if($o.launch_id-eq$LaunchId-and$o.owner_pid-eq$created.ProcessId){$view=Get-CimInstance Win32_Process -Filter ('ProcessId='+$created.ProcessId);break}};if(!(Get-Process -Id $created.ProcessId -ErrorAction SilentlyContinue)){break}}
if(!$view){Atomic (Join-Path $root 'failure.json') ([ordered]@{launch_id=$LaunchId;campaign_id=$CampaignId;reason='bootstrap_not_acknowledged';pid=$created.ProcessId;stdout_path=$out;stderr_path=$err});throw 'campaign bootstrap not acknowledged'}
Atomic (Join-Path $root 'receipt.json') ([ordered]@{schema_version='nora.phase2_firewall_campaign_launch_receipt_v1';launch_id=$LaunchId;campaign_id=$CampaignId;intent_sha256=Hash (Join-Path $root 'intent.json');pid=$created.ProcessId;process_start_utc=([datetime]$view.CreationDate).ToUniversalTime().ToString('o');executable_path=$view.ExecutablePath;command_line=$view.CommandLine;owner_path=$owner;owner_sha256=Hash $owner;stdout_path=$out;stderr_path=$err;acknowledged_utc=(Get-Date).ToUniversalTime().ToString('o')})
Get-Content (Join-Path $root 'receipt.json') -Raw
