[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][ValidateSet('preconditions','restore','rollback','postflight')][string]$Mode,
 [Parameter(Mandatory=$true)][string]$EvidenceRoot,
 [Parameter(Mandatory=$true)][string]$RepositoryCommit,
 [Parameter(Mandatory=$true)][string]$HelperSha256,
 [Parameter(Mandatory=$true)][string]$RestorationScriptSha256,
 [Parameter(Mandatory=$true)][string]$PacketId
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$Guid='{AE6A1199-33B0-4109-B850-F1BB61AF0F6B}';$DisplayName='MetaTrader 5 Strategy Tester Agent';$Program='C:\Program Files\Darwinex MetaTrader 5\metatester64.exe';$ProgramSha256='19c1c41cf4a32b7ad9e4a4b1b028364d7ca85b20ba08e9e4cc27bf209f9764ed';$DeploymentRoot='C:\NoraEvidence\Phase2\frt1r2-inert-aa7ee49';$Helper=Join-Path $DeploymentRoot 'phase2-operator-state.ps1';$EvidenceDir=Join-Path $EvidenceRoot ('frt1r3-tester-rule-restoration-'+$PacketId)
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Atomic([string]$Path,$Value){$full=[IO.Path]::GetFullPath($Path);$root=[IO.Path]::GetFullPath($EvidenceRoot).TrimEnd('\');if(!$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'artifact outside evidence root'};$parent=Split-Path -Parent $full;New-Item -ItemType Directory -Force -Path $parent|Out-Null;$tmp=$full+'.partial.'+[guid]::NewGuid().ToString('N');[IO.File]::WriteAllText($tmp,($Value|ConvertTo-Json -Depth 20 -Compress),[Text.UTF8Encoding]::new($false));$s=[IO.File]::Open($tmp,'Open','ReadWrite','None');$s.Flush($true);$s.Dispose();if(Test-Path -LiteralPath $full){throw 'immutable artifact already exists'};[IO.File]::Move($tmp,$full)}
function Rule([string]$Store){$rs=@(Get-NetFirewallRule -PolicyStore $Store -Name $Guid -ErrorAction Stop);if($rs.Count-ne1){throw ('target rule cardinality '+$Store)};$r=$rs[0];$app=@(Get-NetFirewallApplicationFilter -AssociatedNetFirewallRule $r);$svc=@(Get-NetFirewallServiceFilter -AssociatedNetFirewallRule $r);$addr=@(Get-NetFirewallAddressFilter -AssociatedNetFirewallRule $r);$port=@(Get-NetFirewallPortFilter -AssociatedNetFirewallRule $r);$ifalias=@(Get-NetFirewallInterfaceFilter -AssociatedNetFirewallRule $r);$iface=@(Get-NetFirewallInterfaceTypeFilter -AssociatedNetFirewallRule $r);$sec=@(Get-NetFirewallSecurityFilter -AssociatedNetFirewallRule $r);if($app.Count-ne1-or$svc.Count-ne1-or$addr.Count-ne1-or$port.Count-ne1-or$ifalias.Count-ne1-or$iface.Count-ne1-or$sec.Count-ne1){throw ('target filter cardinality '+$Store)};[ordered]@{store=$Store;name=[string]$r.Name;instance_id=[string]$r.InstanceID;display_name=[string]$r.DisplayName;description=[string]$r.Description;owner=[string]$r.Owner;group=[string]$r.Group;enabled=[bool]$r.Enabled;direction=[string]$r.Direction;action=[string]$r.Action;profile=[string]$r.Profile;edge_traversal=[string]$r.EdgeTraversalPolicy;policy_store_source=[string]$r.PolicyStoreSource;policy_store_source_type=[string]$r.PolicyStoreSourceType;program=[string]$app[0].Program;package=[string]$app[0].Package;service=[string]$svc[0].Service;local_address=[string]$addr[0].LocalAddress;remote_address=[string]$addr[0].RemoteAddress;protocol=[string]$port[0].Protocol;local_port=[string]$port[0].LocalPort;remote_port=[string]$port[0].RemotePort;icmp_type=[string]$port[0].IcmpType;interface_alias=[string]$ifalias[0].InterfaceAlias;interface_type=[string]$iface[0].InterfaceType;authentication=[string]$sec[0].Authentication;encryption=[string]$sec[0].Encryption;override_block_rules=[bool]$sec[0].OverrideBlockRules;local_user=[string]$sec[0].LocalUser;remote_user=[string]$sec[0].RemoteUser}}
function AssertRule($V,[bool]$Enabled){if($V.name-ne$Guid-or$V.instance_id-ne$Guid-or$V.display_name-ne$DisplayName-or$V.description-ne''-or$V.owner-ne''-or$V.group-ne''-or$V.enabled-ne$Enabled-or$V.direction-ne'Inbound'-or$V.action-ne'Allow'-or$V.profile-ne'Domain, Private'-or$V.edge_traversal-ne'Block'-or$V.policy_store_source-ne'PersistentStore'-or$V.policy_store_source_type-ne'Local'-or$V.program-ne$Program-or$V.package-ne''-or$V.service-ne'Any'-or$V.local_address-ne'Any'-or$V.remote_address-ne'Any'-or$V.protocol-ne'TCP'-or$V.local_port-ne'Any'-or$V.remote_port-ne'Any'-or$V.icmp_type-ne'Any'-or$V.interface_alias-ne'Any'-or$V.interface_type-ne'Any'-or$V.authentication-ne'NotRequired'-or$V.encryption-ne'NotRequired'-or$V.override_block_rules-or$V.local_user-ne'Any'-or$V.remote_user-ne'Any'){throw 'tester rule semantic mismatch'}}
function Canonical($Value){$Value|ConvertTo-Json -Depth 30 -Compress}
function HelperInventory(){if(!(Test-Path -LiteralPath $Helper -PathType Leaf)){throw 'missing deployed helper'};if((Hash $Helper)-ne$HelperSha256){throw 'deployed helper hash mismatch'};$out=@(& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Helper -Mode inventory -EvidenceRoot $EvidenceRoot -QualificationId 'frt1r2-live-20260717T192223Z');if($LASTEXITCODE-ne0){throw 'helper inventory failed'};$json=($out -join '')|ConvertFrom-Json;if($json.verdict-ne'PASS'-or$json.active_job_count-ne0-or$json.pending_job_count-ne0-or$json.unresolved_prepared_job_count-ne0-or$json.scheduled_nora_task_count-ne0){throw 'helper inventory safety counts failed'};$json}
function Common(){if($RepositoryCommit-notmatch'^[0-9a-f]{40}$'-or$HelperSha256-notmatch'^[0-9a-f]{64}$'-or$RestorationScriptSha256-notmatch'^[0-9a-f]{64}$'-or$PacketId-notmatch'^[A-Za-z0-9._-]{3,128}$'){throw 'invalid packet identity'};if((Hash $PSCommandPath)-ne$RestorationScriptSha256){throw 'deployed restoration script hash mismatch'};$profiles=@(Get-NetFirewallProfile -PolicyStore ActiveStore -ErrorAction Stop);if($profiles.Count-ne3-or@($profiles|Where-Object{!$_.Enabled}).Count-ne0){throw 'firewall profiles must be exactly three and enabled'};$nora=@(Get-NetFirewallRule -PolicyStore ActiveStore -ErrorAction Stop|Where-Object{([string]$_.Name).ToLowerInvariant().StartsWith('noraphase2containment-')-or([string]$_.Group).ToLowerInvariant().StartsWith('noraphase2containment-')});if($nora.Count-ne0){throw 'Nora rules remain'};$proc=@(Get-Process terminal64,metatester64 -ErrorAction SilentlyContinue);if($proc.Count-ne0){throw 'terminal_or_tester_exists'};if(!(Test-Path -LiteralPath $Program -PathType Leaf)-or(Hash $Program)-ne$ProgramSha256){throw 'accepted tester program identity mismatch'};$inventory=HelperInventory;[ordered]@{profiles=@($profiles|ForEach-Object{[ordered]@{name=[string]$_.Name;enabled=[bool]$_.Enabled}});nora_rule_count=$nora.Count;terminal_tester_process_count=$proc.Count;restoration_script_sha256=Hash $PSCommandPath;helper_inventory=$inventory}}
function SemanticRule($R){
 $apps=@(Get-NetFirewallApplicationFilter -AssociatedNetFirewallRule $R -ErrorAction Stop|Sort-Object Program,Package|ForEach-Object{[ordered]@{program=[string]$_.Program;package=[string]$_.Package}})
 $services=@(Get-NetFirewallServiceFilter -AssociatedNetFirewallRule $R -ErrorAction Stop|Sort-Object Service|ForEach-Object{[ordered]@{service=[string]$_.Service}})
 $addresses=@(Get-NetFirewallAddressFilter -AssociatedNetFirewallRule $R -ErrorAction Stop|Sort-Object LocalAddress,RemoteAddress|ForEach-Object{[ordered]@{local_address=[string]$_.LocalAddress;remote_address=[string]$_.RemoteAddress}})
 $ports=@(Get-NetFirewallPortFilter -AssociatedNetFirewallRule $R -ErrorAction Stop|Sort-Object Protocol,LocalPort,RemotePort,IcmpType|ForEach-Object{[ordered]@{protocol=[string]$_.Protocol;local_port=[string]$_.LocalPort;remote_port=[string]$_.RemotePort;icmp_type=[string]$_.IcmpType}})
 $interfaces=@(Get-NetFirewallInterfaceFilter -AssociatedNetFirewallRule $R -ErrorAction Stop|Sort-Object InterfaceAlias|ForEach-Object{[ordered]@{interface_alias=[string]$_.InterfaceAlias}})
 $interfaceTypes=@(Get-NetFirewallInterfaceTypeFilter -AssociatedNetFirewallRule $R -ErrorAction Stop|Sort-Object InterfaceType|ForEach-Object{[ordered]@{interface_type=[string]$_.InterfaceType}})
 $security=@(Get-NetFirewallSecurityFilter -AssociatedNetFirewallRule $R -ErrorAction Stop|Sort-Object Authentication,Encryption,OverrideBlockRules,LocalUser,RemoteUser|ForEach-Object{[ordered]@{authentication=[string]$_.Authentication;encryption=[string]$_.Encryption;override_block_rules=[bool]$_.OverrideBlockRules;local_user=[string]$_.LocalUser;remote_user=[string]$_.RemoteUser}})
 [ordered]@{name=[string]$R.Name;instance_id=[string]$R.InstanceID;display_name=[string]$R.DisplayName;description=[string]$R.Description;owner=[string]$R.Owner;enabled=[bool]$R.Enabled;direction=[string]$R.Direction;action=[string]$R.Action;profile=[string]$R.Profile;group=[string]$R.Group;edge_traversal=[string]$R.EdgeTraversalPolicy;policy_store_source=[string]$R.PolicyStoreSource;policy_store_source_type=[string]$R.PolicyStoreSourceType;applications=$apps;services=$services;addresses=$addresses;ports=$ports;interfaces=$interfaces;interface_types=$interfaceTypes;security=$security}
}
function UnrelatedDigest(){ $items=@(Get-NetFirewallRule -PolicyStore ActiveStore -ErrorAction Stop|Where-Object{$_.Name-ne$Guid}|Sort-Object Name,InstanceID,PolicyStoreSource|ForEach-Object{SemanticRule $_});$text=Canonical $items;$bytes=[Text.Encoding]::UTF8.GetBytes($text);([Security.Cryptography.SHA256]::Create().ComputeHash($bytes)|ForEach-Object{$_.ToString('x2')})-join''}
function AssertAbsent(){if(@(Get-NetFirewallRule -PolicyStore PersistentStore -Name $Guid -ErrorAction SilentlyContinue).Count-ne0-or@(Get-NetFirewallRule -PolicyStore ActiveStore -Name $Guid -ErrorAction SilentlyContinue).Count-ne0){throw 'target GUID already exists'};if(@(Get-NetFirewallRule -PolicyStore PersistentStore -DisplayName $DisplayName -ErrorAction SilentlyContinue).Count-ne0-or@(Get-NetFirewallRule -PolicyStore ActiveStore -DisplayName $DisplayName -ErrorAction SilentlyContinue).Count-ne0){throw 'target display name conflicts'}}
if($Mode-eq'preconditions'){$common=Common;AssertAbsent;[ordered]@{verdict='PASS';target_rule='ABSENT';accepted_program=$Program;common=$common}|ConvertTo-Json -Depth 30 -Compress;exit 0}
if($Mode-eq'restore'){$common=Common;AssertAbsent;$beforeDigest=UnrelatedDigest;$before=[ordered]@{schema_version='nora.phase2_tester_rule_restoration_before_v1';packet_id=$PacketId;repository_commit=$RepositoryCommit;target_rule_absent=$true;unrelated_digest=$beforeDigest;captured_utc=(Get-Date).ToUniversalTime().ToString('o')};Atomic (Join-Path $EvidenceDir 'before.json') $before;New-NetFirewallRule -PolicyStore PersistentStore -Name $Guid -DisplayName $DisplayName -Description '' -Direction Inbound -Action Allow -Profile Domain,Private -Program $Program -Protocol TCP -LocalPort Any -RemotePort Any -LocalAddress Any -RemoteAddress Any -InterfaceType Any -Service Any -Authentication NotRequired -Encryption NotRequired -OverrideBlockRules False -EdgeTraversalPolicy Block -Enabled False -ErrorAction Stop|Out-Null;$after=Rule 'PersistentStore';AssertRule $after $false;$activeAfter=Rule 'ActiveStore';AssertRule $activeAfter $false;$afterDigest=UnrelatedDigest;if($afterDigest-ne$beforeDigest){throw 'unrelated firewall semantic identity changed'};$receipt=[ordered]@{schema_version='nora.phase2_tester_rule_restoration_after_v1';packet_id=$PacketId;repository_commit=$RepositoryCommit;operation='create_exact_tester_rule_disabled';persistent=$after;active=$activeAfter;before_unrelated_digest=$beforeDigest;after_unrelated_digest=$afterDigest;completed_utc=(Get-Date).ToUniversalTime().ToString('o')};Atomic (Join-Path $EvidenceDir 'after.json') $receipt;[ordered]@{verdict='PASS';before_path=(Join-Path $EvidenceDir 'before.json');after_path=(Join-Path $EvidenceDir 'after.json')}|ConvertTo-Json -Compress;exit 0}
if($Mode-eq'rollback'){$common=Common;$afterPath=Join-Path $EvidenceDir 'after.json';if(!(Test-Path -LiteralPath $afterPath -PathType Leaf)){throw 'missing restoration receipt'};$after=Get-Content -LiteralPath $afterPath -Raw|ConvertFrom-Json;if($after.packet_id-ne$PacketId){throw 'restoration packet identity mismatch'};$persistent=Rule 'PersistentStore';$active=Rule 'ActiveStore';AssertRule $persistent $false;AssertRule $active $false;Remove-NetFirewallRule -PolicyStore PersistentStore -Name $Guid -ErrorAction Stop;$remaining=@(Get-NetFirewallRule -PolicyStore PersistentStore -Name $Guid -ErrorAction SilentlyContinue).Count+@(Get-NetFirewallRule -PolicyStore ActiveStore -Name $Guid -ErrorAction SilentlyContinue).Count;if($remaining-ne0){throw 'rollback left target rule'};[ordered]@{verdict='PASS';operation='remove_exact_restored_rule';packet_id=$PacketId}|ConvertTo-Json -Compress;exit 0}
if($Mode-eq'postflight'){$common=Common;$beforePath=Join-Path $EvidenceDir 'before.json';$afterPath=Join-Path $EvidenceDir 'after.json';if(!(Test-Path -LiteralPath $beforePath -PathType Leaf)-or!(Test-Path -LiteralPath $afterPath -PathType Leaf)){throw 'missing restoration evidence'};$before=Get-Content -LiteralPath $beforePath -Raw|ConvertFrom-Json;$after=Get-Content -LiteralPath $afterPath -Raw|ConvertFrom-Json;if($before.schema_version-ne'nora.phase2_tester_rule_restoration_before_v1'-or$before.packet_id-ne$PacketId-or$before.repository_commit-ne$RepositoryCommit-or!$before.target_rule_absent){throw 'restoration before record identity mismatch'};if($after.schema_version-ne'nora.phase2_tester_rule_restoration_after_v1'-or$after.packet_id-ne$PacketId-or$after.repository_commit-ne$RepositoryCommit-or$after.operation-ne'create_exact_tester_rule_disabled'){throw 'restoration after receipt identity mismatch'};$persistent=Rule 'PersistentStore';$active=Rule 'ActiveStore';AssertRule $persistent $false;AssertRule $active $false;$persistentCanonical=Canonical $persistent;$receiptPersistentCanonical=Canonical $after.persistent;$activeCanonical=Canonical $active;$receiptActiveCanonical=Canonical $after.active;if($persistentCanonical-ne$receiptPersistentCanonical-or$activeCanonical-ne$receiptActiveCanonical){throw 'restoration after receipt semantic mismatch'};$currentDigest=UnrelatedDigest;if($before.unrelated_digest-ne$after.before_unrelated_digest-or$after.before_unrelated_digest-ne$after.after_unrelated_digest-or$currentDigest-ne$after.after_unrelated_digest){throw 'unrelated firewall semantic identity changed'};[ordered]@{verdict='PASS';target_rule_enabled=$false;unrelated_firewall_unchanged=$true;after_receipt_reopened=$true;common=$common}|ConvertTo-Json -Depth 30 -Compress;exit 0}
