param(
 [Parameter(Mandatory=$true)][ValidateSet('preflight','prepare','launch','status','package','record-import','harden-acl')][string]$Mode,
 [string]$RunId,
 [string]$IncomingRoot,
 [ValidateSet('GDAXI','AUDCAD')][string]$Symbol,
 [long]$BeforeBarCount,
 [long]$AfterBarCount,
 [string]$BeforeEarliest,
 [string]$BeforeLatest,
 [string]$AfterEarliest,
 [string]$AfterLatest,
 [string]$EvaluationPath,
 [string]$ImportRecordPath,
 [string]$EvidenceRoot='C:\NoraEvidence\Phase2'
)
$ErrorActionPreference='Stop'
$schema='nora.phase2_persistent_evidence_runner_v1'
$terminal='C:\Program Files\Darwinex MetaTrader 5\terminal64.exe'
$required=@('SYSTEM','BA','')

function Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()}
function AtomicJson([string]$Path,$Value){$tmp=$Path+'.partial.'+[guid]::NewGuid().ToString('N');$Value|ConvertTo-Json -Depth 12 -Compress|Set-Content -LiteralPath $tmp -Encoding utf8 -NoNewline;Move-Item -LiteralPath $tmp -Destination $Path}
function NeedRunId(){if(!$RunId -or $RunId -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]{2,127}$'){throw 'invalid run identity'}}
function Paths(){NeedRunId;return [ordered]@{incoming=(Join-Path $EvidenceRoot ('incoming\'+$RunId));running=(Join-Path $EvidenceRoot ('runs\'+$RunId+'.running'));complete=(Join-Path $EvidenceRoot ('runs\'+$RunId+'.complete'));returned=(Join-Path $EvidenceRoot ('returned\'+$RunId+'.published'));job=(Join-Path $EvidenceRoot ('jobs\'+$RunId+'.json'));stdout=(Join-Path $EvidenceRoot ('logs\'+$RunId+'.stdout.log'));stderr=(Join-Path $EvidenceRoot ('logs\'+$RunId+'.stderr.log'))}}
function Inventory([string]$Base){@(Get-ChildItem -LiteralPath $Base -File -Recurse -Force|Sort-Object FullName|ForEach-Object{[ordered]@{path=$_.FullName.Substring($Base.Length).TrimStart('\\').Replace('\\','/');size=[int64]$_.Length;sha256=Hash $_.FullName}})}
function Identity(){ $i=[Security.Principal.WindowsIdentity]::GetCurrent();[ordered]@{name=$i.Name;sid=$i.User.Value} }
function AclView([string]$Path){$a=Get-Acl -LiteralPath $Path;[ordered]@{owner=$a.Owner;sddl=$a.Sddl;protected=$a.AreAccessRulesProtected;access=@($a.Access|ForEach-Object{[ordered]@{identity=$_.IdentityReference.Value;rights=[string]$_.FileSystemRights;type=[string]$_.AccessControlType;inherited=$_.IsInherited}})}}
function RuleSid($Rule){try{return $Rule.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value}catch{throw 'unresolvable ACL principal'}}
function AssertSecureAcl([string]$Path){$a=Get-Acl -LiteralPath $Path;if(!$a.AreAccessRulesProtected){throw 'evidence ACL inheritance enabled'};$broad='S-1-1-0','S-1-5-11','S-1-5-32-545';foreach($rule in @($a.Access)){if(($broad -contains (RuleSid $rule)) -and ([string]$rule.FileSystemRights -match 'Write|Modify|FullControl|Delete')){throw 'broad evidence write ACL'}}}
function SecureAcl([string]$Path,[bool]$Container,[string]$RunnerSid){$acl=if($Container){New-Object Security.AccessControl.DirectorySecurity}else{New-Object Security.AccessControl.FileSecurity};$acl.SetAccessRuleProtection($true,$false);foreach($sidText in @('S-1-5-18','S-1-5-32-544',$RunnerSid)){ $sid=New-Object Security.Principal.SecurityIdentifier($sidText);$inherit=if($Container){[Security.AccessControl.InheritanceFlags]'ContainerInherit, ObjectInherit'}else{[Security.AccessControl.InheritanceFlags]::None};$rule=New-Object Security.AccessControl.FileSystemAccessRule($sid,[Security.AccessControl.FileSystemRights]::FullControl,$inherit,[Security.AccessControl.PropagationFlags]::None,[Security.AccessControl.AccessControlType]::Allow);$acl.AddAccessRule($rule)};$acl.SetOwner((New-Object Security.Principal.SecurityIdentifier($RunnerSid)));Set-Acl -LiteralPath $Path -AclObject $acl}
function WriteJob($paths,[string]$State,$extra=@{}){ $old=if(Test-Path -LiteralPath $paths.job){Get-Content -LiteralPath $paths.job -Raw|ConvertFrom-Json}else{$null};$value=[ordered]@{};if($old){foreach($p in $old.PSObject.Properties){$value[$p.Name]=$p.Value}};$value.schema_version=$schema;$value.run_identifier=$RunId;$value.state=$State;$value.updated_utc=(Get-Date).ToUniversalTime().ToString('o');$value.evidence_root=$EvidenceRoot;$value.runner_identity=Identity;$value.terminal_path=$terminal;$value.paths=$paths;if(!$value.created_utc){$value.created_utc=$value.updated_utc};foreach($p in $extra.PSObject.Properties){$value[$p.Name]=$p.Value};AtomicJson $paths.job $value;return $value }
function RequireSecureRoot(){
 if(!(Test-Path -LiteralPath $EvidenceRoot -PathType Container)){throw 'missing evidence root'}
 $volume=Get-Volume -DriveLetter ([IO.Path]::GetPathRoot($EvidenceRoot).TrimEnd(':','\\'))
 if($volume.HealthStatus -ne 'Healthy'){throw 'unhealthy evidence volume'}
 if($volume.SizeRemaining -lt 5GB){throw 'insufficient evidence free space'}
 $tree=@($EvidenceRoot)+@(Get-ChildItem -LiteralPath $EvidenceRoot -Recurse -Force|ForEach-Object{$_.FullName});foreach($path in $tree){AssertSecureAcl $path}
 return [ordered]@{volume_health=[string]$volume.HealthStatus;free_bytes=[int64]$volume.SizeRemaining;acl=(AclView $EvidenceRoot);secured_path_count=$tree.Count;identity=Identity}
}
function NoTerminal(){if(Get-Process terminal64,metatester64 -ErrorAction SilentlyContinue){throw 'conflicting terminal_or_tester'}}
function NoCampaignJob(){ $jobs=Join-Path $EvidenceRoot 'jobs';if(!(Test-Path -LiteralPath $jobs)){return};foreach($path in @(Get-ChildItem -LiteralPath $jobs -Filter '*.json' -File -ErrorAction Stop)){ $job=Get-Content -LiteralPath $path.FullName -Raw|ConvertFrom-Json;if(@('launched','running','packaging') -contains $job.state){throw 'conflicting persistent campaign job'} } }
function RequireWorker([string]$Incoming){$p=Join-Path $Incoming 'phase-0a-h\windows\execute-ten-strategy-packet.ps1';if(!(Test-Path -LiteralPath $p)){throw 'missing bound packet worker'};return $p}

switch($Mode){
 'preflight' { $root=RequireSecureRoot;NoTerminal;[ordered]@{schema_version=$schema;preflight='pass';evidence_root=$EvidenceRoot;terminal_path=$terminal;root=$root;utc=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json -Depth 12 -Compress }
 'harden-acl' {
   if(!(Test-Path -LiteralPath $EvidenceRoot -PathType Container)){throw 'missing evidence root'}
   $id=Identity;$audit=Join-Path $EvidenceRoot ('acl-audits\'+(Get-Date -Format 'yyyyMMddTHHmmssZ'));New-Item -ItemType Directory -Path $audit -Force|Out-Null
   $before=[ordered]@{schema_version='nora.phase2_evidence_acl_audit_v1';captured_utc=(Get-Date).ToUniversalTime().ToString('o');identity=$id;acl=AclView $EvidenceRoot;inventory=Inventory $EvidenceRoot};AtomicJson (Join-Path $audit 'before.json') $before
   SecureAcl $EvidenceRoot $true $id.sid;foreach($target in @(Get-ChildItem -LiteralPath $EvidenceRoot -Recurse -Force|Sort-Object FullName)){SecureAcl $target.FullName ($target.PSIsContainer) $id.sid}
   $afterAcl=AclView $EvidenceRoot;$after=Inventory $EvidenceRoot;$baseline=@($before.inventory|Where-Object{$_.path -notlike 'acl-audits/*'});$now=@($after|Where-Object{$_.path -notlike 'acl-audits/*'});if((ConvertTo-Json $baseline -Compress) -ne (ConvertTo-Json $now -Compress)){throw 'pre-existing evidence changed during ACL hardening'}
   $probe=Join-Path $EvidenceRoot ('acl-probe-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $probe|Out-Null;$payload=Join-Path $probe 'probe.txt';'phase2-acl-probe'|Set-Content -LiteralPath $payload -Encoding utf8 -NoNewline;$digest=Hash $payload;$final=Join-Path $probe 'final.txt';Move-Item -LiteralPath $payload -Destination $final;if((Hash $final)-ne$digest){throw 'ACL probe hash mismatch'};Remove-Item -LiteralPath $probe -Recurse -Force
   $result=[ordered]@{schema_version='nora.phase2_evidence_acl_audit_v1';result='pass';identity=$id;before_sha256=Hash (Join-Path $audit 'before.json');after_acl=$afterAcl;preexisting_evidence_byte_identical=$true;runner_probe_create_finalize_read_hash_delete=$true;completed_utc=(Get-Date).ToUniversalTime().ToString('o')};AtomicJson (Join-Path $audit 'after.json') $result;$result|ConvertTo-Json -Depth 12 -Compress
 }
 'prepare' { $root=RequireSecureRoot;$p=Paths;foreach($path in @($p.incoming,$p.running,$p.complete,$p.returned,$p.job)){if(Test-Path -LiteralPath $path){throw 'duplicate or stale run identity'}};foreach($dir in @($EvidenceRoot,(Join-Path $EvidenceRoot 'incoming'),(Join-Path $EvidenceRoot 'runs'),(Join-Path $EvidenceRoot 'returned'),(Join-Path $EvidenceRoot 'jobs'),(Join-Path $EvidenceRoot 'logs'))){New-Item -ItemType Directory -Path $dir -Force|Out-Null};New-Item -ItemType Directory -Path $p.incoming|Out-Null;New-Item -ItemType Directory -Path $p.running|Out-Null;WriteJob $p 'prepared' @{prepared_root=$root;run_directory=$p.running}|ConvertTo-Json -Depth 12 -Compress }
 'launch' { $root=RequireSecureRoot;NoTerminal;NoCampaignJob;$p=Paths;if(!(Test-Path -LiteralPath $p.incoming) -or !(Test-Path -LiteralPath $p.running) -or !(Test-Path -LiteralPath $p.job)){throw 'missing prepared run'};$old=Get-Content -LiteralPath $p.job -Raw|ConvertFrom-Json;if($old.state -ne 'prepared'){throw 'launch not idempotent'};$packet=Get-Content -LiteralPath (Join-Path $p.incoming 'execution_packet.json') -Raw|ConvertFrom-Json;$batch=Get-Content -LiteralPath (Join-Path $p.incoming 'final_batch.json') -Raw|ConvertFrom-Json;if($batch.execution_packet_identity -ne $packet.execution_packet_identity){throw 'packet batch mismatch'};foreach($file in @($batch.staged_files)){ $candidate=Join-Path $p.incoming $file.path;if(!(Test-Path -LiteralPath $candidate) -or (Hash $candidate) -ne $file.sha256){throw 'staged role hash mismatch'} };$role=@($packet.native_execution_contract.roles|Where-Object{$_.role -eq 'persistent_windows_evidence_runner'});if($role.Count -ne 1 -or (Hash $PSCommandPath) -ne $role[0].sha256){throw 'persistent runner identity mismatch'};$worker=RequireWorker $p.incoming;$args=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$worker,'-IncomingRoot',$p.incoming,'-RunId',$RunId,'-Symbol',$Symbol,'-BeforeBarCount',$BeforeBarCount,'-AfterBarCount',$AfterBarCount,'-BeforeEarliest',$BeforeEarliest,'-BeforeLatest',$BeforeLatest,'-AfterEarliest',$AfterEarliest,'-AfterLatest',$AfterLatest,'-RunDirectory',$p.running,'-EvidenceRoot',$EvidenceRoot);$proc=Start-Process -FilePath powershell.exe -ArgumentList $args -RedirectStandardOutput $p.stdout -RedirectStandardError $p.stderr -PassThru;WriteJob $p 'launched' @{worker_pid=$proc.Id;worker_started_utc=(Get-Date).ToUniversalTime().ToString('o');worker_executable_path=$worker;worker_sha256=Hash $worker;configuration_identity=Hash (Join-Path $p.incoming 'execution_packet.json')}|ConvertTo-Json -Depth 12 -Compress }
 'status' { $p=Paths;if(!(Test-Path -LiteralPath $p.job)){throw 'missing durable run state'};$job=Get-Content -LiteralPath $p.job -Raw|ConvertFrom-Json;$running=Test-Path -LiteralPath $p.running;$complete=Test-Path -LiteralPath $p.complete;$published=Test-Path -LiteralPath $p.returned;$process=$false;if($job.worker_pid){$process=[bool](Get-Process -Id $job.worker_pid -ErrorAction SilentlyContinue)};$state=if($published -and @('accepted','rejected') -contains $job.state){$job.state}elseif($published){'published'}elseif($complete){'terminal-completed'}elseif($process){'running'}elseif($running){'ambiguous-incomplete'}else{'ambiguous-missing'};if($state -in @('running','terminal-completed','published')){WriteJob $p $state @{}|Out-Null;$job=Get-Content -LiteralPath $p.job -Raw|ConvertFrom-Json};[ordered]@{schema_version=$schema;run_identifier=$RunId;state=$state;durable_job=$job;worker_process_running=$process;running_directory=$running;complete_directory=$complete;published_directory=$published;ssh_disconnect_is_failure=$false}|ConvertTo-Json -Depth 12 -Compress }
 'package' { $p=Paths;if(!(Test-Path -LiteralPath $p.complete)){throw 'terminal completion not durable'};if(Test-Path -LiteralPath $p.returned){throw 'package not idempotent'};if(!$EvaluationPath -or !(Test-Path -LiteralPath $EvaluationPath)){throw 'missing environmental evaluation'};Copy-Item -LiteralPath $EvaluationPath -Destination (Join-Path $p.complete 'environmental-evaluation.json');WriteJob $p 'packaging' @{}|Out-Null;$builder=Join-Path $p.incoming 'phase-0a-h\windows\build-ten-strategy-returned-package.ps1';& $builder -RunDirectory $p.complete -Destination $p.returned;WriteJob $p 'published' @{returned_package_path=$p.returned}|Out-Null;$p.returned }
 'record-import' { $p=Paths;if(!(Test-Path -LiteralPath $p.returned)){throw 'missing published package'};if(!$ImportRecordPath -or !(Test-Path -LiteralPath $ImportRecordPath)){throw 'missing import record'};Copy-Item -LiteralPath $ImportRecordPath -Destination (Join-Path $EvidenceRoot ('jobs\\'+$RunId+'.linux-ingestion.json'));$i=Get-Content -LiteralPath $ImportRecordPath -Raw|ConvertFrom-Json;$state=if($i.classification -eq 'PASS_EXACT'){'accepted'}else{'rejected'};WriteJob $p $state @{linux_ingestion_identity=$i.ingestion_identity;linux_classification=$i.classification}|ConvertTo-Json -Depth 12 -Compress }
}
