[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][ValidateSet('publish','verify')][string]$Mode,
 [string]$PlanPath,
 [Parameter(Mandatory=$true)][string]$EnvelopePath,
 [Parameter(Mandatory=$true)][string]$EvidenceRoot,
 [Parameter(Mandatory=$true)][string]$ExpectedCaseId
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
$schema='nora.phase2_case_envelope_v1';$packageSchema='nora.phase2_containment_atomic_evidence_v1'
function Fail([string]$m){throw ('NORA_CASE_ENVELOPE:'+$m)}
function Hash([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256 -ErrorAction Stop).Hash.ToLowerInvariant()}
function HashBytes([byte[]]$b){([Security.Cryptography.SHA256]::Create().ComputeHash($b)|ForEach-Object{$_.ToString('x2')})-join''}
function UnderRoot([string]$p){$root=[IO.Path]::GetFullPath($EvidenceRoot).TrimEnd('\');$full=[IO.Path]::GetFullPath($p);if(!$full.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)){Fail 'outside_root'};$cursor=Get-Item -LiteralPath $root -Force;foreach($part in $full.Substring($root.Length).TrimStart('\').Split('\',[StringSplitOptions]::RemoveEmptyEntries)){$cursor=Get-Item -LiteralPath (Join-Path $cursor.FullName $part) -Force;if(($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){Fail 'reparse_path'}};$full}
function EntryBytes($archive,[string]$name){$entries=@($archive.Entries|Where-Object{$_.FullName-eq$name});if($entries.Count-ne1){Fail ('missing_or_duplicate_'+$name)};$s=$entries[0].Open();$m=New-Object IO.MemoryStream;$s.CopyTo($m);$s.Dispose();$bytes=$m.ToArray();$m.Dispose();return ,$bytes}
function ValidatePackage($spec,$plan){
 $zip=$null
 $path=UnderRoot ([string]$spec.windows_path);if(!(Test-Path -LiteralPath $path -PathType Leaf)){Fail 'missing_package'}
 $size=[int64](Get-Item -LiteralPath $path).Length;$digest=Hash $path;if($size-ne[int64]$spec.package_size-or$digest-ne[string]$spec.package_sha256){Fail 'package_identity'}
 $file=[IO.File]::Open($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$zip=New-Object IO.Compression.ZipArchive($file,[IO.Compression.ZipArchiveMode]::Read,$false);$names=@($zip.Entries|ForEach-Object{$_.FullName});if(@($names|Sort-Object -Unique).Count-ne$names.Count){Fail 'duplicate_member'};$summaryBytes=EntryBytes $zip 'summary.json';$manifestBytes=EntryBytes $zip 'manifest.json';$summary=[Text.Encoding]::UTF8.GetString($summaryBytes)|ConvertFrom-Json;$manifest=[Text.Encoding]::UTF8.GetString($manifestBytes)|ConvertFrom-Json;if($summary.schema-ne$packageSchema-or$manifest.schema-ne$packageSchema){Fail 'package_schema'};foreach($field in @('run_id','case_id','operation_id','repository_commit')){if([string]$summary.$field-ne[string]$manifest.$field){Fail ('package_'+$field)}};if($summary.run_id-ne$plan.case_id-or$summary.case_id-ne$plan.case_id-or$summary.operation_id-ne$spec.operation_id-or$summary.repository_commit-ne$plan.repository_commit){Fail 'foreign_package'};if([int]$summary.original_containment_exit_code-ne[int]$spec.original_child_exit-or[int]$spec.expected_exit-ne[int]$spec.original_child_exit-or$spec.operation_verdict-ne'PASS'){Fail 'operation_exit_or_verdict'};if($summary.script_hashes.runner-ne$plan.identities.runner-or$summary.script_hashes.publisher-ne$plan.identities.publisher){Fail 'component_identity'};$listed=@($manifest.members);if($listed.Count-ne($zip.Entries.Count-2)){Fail 'manifest_count'};foreach($item in $listed){$bytes=EntryBytes $zip ([string]$item.path);if($bytes.Length-ne[int64]$item.size-or(HashBytes $bytes)-ne[string]$item.sha256){Fail 'member_identity'}};$pre=HashBytes ((EntryBytes $zip 'pre_state.json')+(EntryBytes $zip 'firewall_pre.json'));$post=HashBytes ((EntryBytes $zip 'post_state.json')+(EntryBytes $zip 'firewall_post.json'));[ordered]@{summary=$summary;size=$size;sha256=$digest;manifest_sha256=HashBytes $manifestBytes;pre=$pre;post=$post}}finally{if($zip){$zip.Dispose()};$file.Dispose()}
 if($summary.script_hashes.containment-ne$plan.identities.containment){Fail 'component_identity'}
}
function Build($plan){
 if($plan.case_id-ne$ExpectedCaseId-or$plan.repository_commit-notmatch'^[0-9a-f]{40}$'){Fail 'case_identity'}
 [object[]]$sequence=@($plan.declared_sequence);[object[]]$specs=@($plan.operations);if(!$sequence.Count-or$sequence.Count-ne$specs.Count-or@($sequence|Sort-Object -Unique).Count-ne$sequence.Count){Fail 'sequence'}
 $paths=@($specs|ForEach-Object{[string]$_.windows_path});if(@($paths|Sort-Object -Unique).Count-ne$paths.Count){Fail 'duplicate_package'}
 $rendered=@();for($i=0;$i-lt$specs.Count;$i++){$spec=$specs[$i];if($sequence[$i]-ne$spec.operation_id){Fail 'order'};$pred=if($i-eq0){$null}else{[string]$sequence[$i-1]};if([string]$spec.predecessor_operation_id-ne[string]$pred){Fail 'predecessor'};$verified=ValidatePackage $spec $plan;$retrieval=$spec.retrieval;if($retrieval.receipt_sha256-notmatch'^[0-9a-f]{64}$'-or$retrieval.fedora_package_sha256-ne$verified.sha256-or$retrieval.verification_result-ne'PASS'){Fail 'retrieval_binding'};$rendered+=,[ordered]@{operation_id=[string]$spec.operation_id;operation_type=[string]$spec.operation_type;package=[ordered]@{windows_path=[string]$spec.windows_path;size=$verified.size;sha256=$verified.sha256;manifest_sha256=$verified.manifest_sha256};original_child_exit=[int]$spec.original_child_exit;helper_exit=[int]$spec.helper_exit;expected_exit=[int]$spec.expected_exit;operation_verdict='PASS';started_utc=[string]$verified.summary.started_at;finished_utc=[string]$verified.summary.finished_at;precondition_state_sha256=$verified.pre;postcondition_state_sha256=$verified.post;predecessor_operation_id=$pred;causal_relationship=[string]$spec.causal_relationship;cleanup_recovery_relationship=$spec.cleanup_recovery_relationship;retrieval=$retrieval}}
 if($plan.case_type-eq'abandoned_reuse'){if($rendered.Count-ne6-or$rendered[3].operation_type-ne'cleanup'){Fail 'abandoned_sequence'};foreach($i in @(4,5)){if($rendered[$i].cleanup_recovery_relationship-ne'after_cleanup:cleanup'){Fail 'after_cleanup_relationship'}}}
 [ordered]@{schema_version=$schema;case_id=[string]$plan.case_id;case_type=[string]$plan.case_type;repository_commit=[string]$plan.repository_commit;identities=$plan.identities;declared_sequence=@($sequence);operations=@($rendered);case_invariants=$plan.case_invariants;final_verdict='PASS';failure_stage=$null;failure_reason=$null;published_utc=[string]$plan.published_utc}
}
$destination=[IO.Path]::GetFullPath($EnvelopePath);$parent=Split-Path -Parent $destination;if(!$destination.StartsWith([IO.Path]::GetFullPath($EvidenceRoot).TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)){Fail 'envelope_outside_root'}
if($Mode-eq'verify'){$value=Get-Content -LiteralPath (UnderRoot $destination) -Raw|ConvertFrom-Json;if($value.schema_version-ne$schema-or$value.case_id-ne$ExpectedCaseId-or$value.final_verdict-ne'PASS'){Fail 'invalid_envelope'};$value|ConvertTo-Json -Depth 32 -Compress;exit 0}
if(!(Test-Path -LiteralPath $PlanPath -PathType Leaf)){Fail 'missing_plan'};$plan=Get-Content -LiteralPath (UnderRoot $PlanPath) -Raw|ConvertFrom-Json;$envelope=Build $plan;$payload=($envelope|ConvertTo-Json -Depth 32 -Compress);New-Item -ItemType Directory -Force -Path $parent|Out-Null;$partial=$destination+'.partial.'+[guid]::NewGuid().ToString('N');[IO.File]::WriteAllText($partial,$payload,[Text.UTF8Encoding]::new($false));$stream=[IO.File]::Open($partial,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$stream.Flush($true);$stream.Dispose();if(Test-Path -LiteralPath $destination){if((Hash $destination)-ne(Hash $partial)){Remove-Item -LiteralPath $partial -Force;Fail 'conflicting_envelope'};Remove-Item -LiteralPath $partial -Force}else{[IO.File]::Move($partial,$destination)};[ordered]@{path=$destination;size=[int64](Get-Item -LiteralPath $destination).Length;sha256=Hash $destination}|ConvertTo-Json -Compress
