//! Locked Phase 2A Layer-1 indicators. `None` is the sole unavailable value.
use chrono::NaiveDate;
use crate::{CanonicalM1Bar, TimeContract}; use crate::time::ClockModel;
pub type Series=Vec<Option<f64>>; pub type Result<T>=std::result::Result<T,String>;
fn period(n:usize)->Result<()> {if n==0{Err("period must be positive".into())}else{Ok(())}}
fn finite(x:&[f64])->Result<()> {if x.iter().all(|v|v.is_finite()){Ok(())}else{Err("non-finite indicator input".into())}}
pub fn sma(x:&[f64],n:usize)->Result<Series>{period(n)?;finite(x)?;Ok((0..x.len()).map(|i|if i+1<n{None}else{Some(x[i+1-n..=i].iter().sum::<f64>()/n as f64)}).collect())}
pub fn ema(x:&[f64],n:usize)->Result<Series>{period(n)?;finite(x)?;let mut o=vec![None;x.len()];if x.len()>=n{let mut e=x[..n].iter().sum::<f64>()/n as f64;o[n-1]=Some(e);let a=2./(n as f64+1.);for i in n..x.len(){e+=a*(x[i]-e);o[i]=Some(e)}}Ok(o)}
pub fn wilder(x:&[f64],n:usize)->Result<Series>{period(n)?;let mut o=vec![None;x.len()];if x.len()>=n{let mut v=x[..n].iter().sum::<f64>()/n as f64;o[n-1]=Some(v);for i in n..x.len(){v=(v*(n-1)as f64+x[i])/n as f64;o[i]=Some(v)}}Ok(o)}
pub fn atr(h:&[f64],l:&[f64],c:&[f64],n:usize)->Result<Series>{if h.len()!=l.len()||l.len()!=c.len(){return Err("OHLC lengths differ".into())}let tr=(0..h.len()).map(|i|if i==0{h[i]-l[i]}else{(h[i]-l[i]).max((h[i]-c[i-1]).abs()).max((l[i]-c[i-1]).abs())}).collect::<Vec<_>>();wilder(&tr,n)}
pub fn rsi(x:&[f64],n:usize)->Result<Series>{period(n)?;let mut o=vec![None;x.len()];if x.len()<=n{return Ok(o)}let(mut g,mut l)=(0.,0.);for i in 1..=n{let d=x[i]-x[i-1];g+=d.max(0.);l+=(-d).max(0.)}g/=n as f64;l/=n as f64;for i in n..x.len(){if i>n{let d=x[i]-x[i-1];g=(g*(n-1)as f64+d.max(0.))/n as f64;l=(l*(n-1)as f64+(-d).max(0.))/n as f64}o[i]=Some(if l==0.{if g==0.{50.}else{100.}}else{100.-100./(1.+g/l)})}Ok(o)}
pub fn roc(x:&[f64],n:usize)->Result<Series>{period(n)?;Ok((0..x.len()).map(|i|if i<n||x[i-n]==0.{None}else{Some((x[i]/x[i-n]-1.)*100.)}).collect())}
pub fn er(x:&[f64],n:usize)->Result<Series>{period(n)?;Ok((0..x.len()).map(|i|if i<n{None}else{let v=x[i-n+1..=i].windows(2).map(|p|(p[1]-p[0]).abs()).sum::<f64>();Some(if v==0.{0.}else{(x[i]-x[i-n]).abs()/v})}).collect())}
pub fn kama(x:&[f64],n:usize,fast:usize,slow:usize)->Result<Series>{period(n)?;period(fast)?;period(slow)?;let e=er(x,n)?;let mut o=vec![None;x.len()];if x.len()>n{let(mut k,fc,sc)=(x[n],2./(fast as f64+1.),2./(slow as f64+1.));o[n]=Some(k);for i in n+1..x.len(){let a=(e[i].unwrap()*(fc-sc)+sc).powi(2);k+=a*(x[i]-k);o[i]=Some(k)}}Ok(o)}
pub fn macd(x:&[f64],fast:usize,slow:usize,signal:usize)->Result<(Series,Series,Series)>{if fast>=slow{return Err("MACD fast must be less than slow".into())}let a=ema(x,fast)?;let b=ema(x,slow)?;let m=(0..x.len()).map(|i|match(a[i],b[i]){(Some(x),Some(y))=>Some(x-y),_=>None}).collect::<Series>();let vals=m.iter().flatten().copied().collect::<Vec<_>>();let sig0=ema(&vals,signal)?;let mut s=vec![None;x.len()];let mut j=0;for i in 0..x.len(){if m[i].is_some(){s[i]=sig0[j];j+=1}}let hist=(0..x.len()).map(|i|match(m[i],s[i]){(Some(a),Some(b))=>Some(a-b),_=>None}).collect();Ok((m,s,hist))}
pub fn highest(x:&[f64],n:usize)->Result<Series>{period(n)?;Ok((0..x.len()).map(|i|if i+1<n{None}else{Some(x[i+1-n..=i].iter().copied().fold(f64::NEG_INFINITY,f64::max))}).collect())} pub fn lowest(x:&[f64],n:usize)->Result<Series>{period(n)?;Ok((0..x.len()).map(|i|if i+1<n{None}else{Some(x[i+1-n..=i].iter().copied().fold(f64::INFINITY,f64::min))}).collect())}
pub fn cci(h:&[f64],l:&[f64],c:&[f64],n:usize)->Result<Series>{period(n)?;let t=(0..c.len()).map(|i|(h[i]+l[i]+c[i])/3.).collect::<Vec<_>>();let mut o=vec![None;c.len()];for i in n-1..c.len(){let w=&t[i+1-n..=i];let m=w.iter().sum::<f64>()/n as f64;let d=w.iter().map(|v|(v-m).abs()).sum::<f64>()/n as f64;o[i]=Some(if d==0.{0.}else{(t[i]-m)/(0.015*d)})}Ok(o)}
pub fn stochastic(h:&[f64],l:&[f64],c:&[f64],k:usize,d:usize)->Result<(Series,Series)>{period(d)?;let hi=highest(h,k)?;let lo=lowest(l,k)?;let p=(0..c.len()).map(|i|match(hi[i],lo[i]){(Some(a),Some(b))=>Some(if a==b{50.}else{100.*(c[i]-b)/(a-b)}),_=>None}).collect::<Series>();let q=(0..c.len()).map(|i|if i+1<d{None}else{p[i+1-d..=i].iter().copied().collect::<Option<Vec<_>>>().map(|v|v.iter().sum::<f64>()/d as f64)}).collect();Ok((p,q))}
pub fn bollinger(x:&[f64],n:usize,k:f64)->Result<(Series,Series,Series,Series)>{period(n)?;let mut mid=vec![None;x.len()];let(mut u,mut l,mut w)=(mid.clone(),mid.clone(),mid.clone());for i in n-1..x.len(){let a=&x[i+1-n..=i];let m=a.iter().sum::<f64>()/n as f64;let s=(a.iter().map(|v|(v-m).powi(2)).sum::<f64>()/n as f64).sqrt();mid[i]=Some(m);u[i]=Some(m+k*s);l[i]=Some(m-k*s);w[i]=Some(if m==0.{0.}else{(2.*k*s)/m})}Ok((mid,u,l,w))}
pub fn keltner(h:&[f64],l:&[f64],c:&[f64],n:usize,k:f64)->Result<(Series,Series,Series)>{let m=ema(c,n)?;let a=atr(h,l,c,n)?;let u=(0..c.len()).map(|i|match(m[i],a[i]){(Some(x),Some(y))=>Some(x+k*y),_=>None}).collect();let d=(0..c.len()).map(|i|match(m[i],a[i]){(Some(x),Some(y))=>Some(x-k*y),_=>None}).collect();Ok((m,u,d))}
pub fn linear_regression(x:&[f64],n:usize)->Result<(Series,Series)>{period(n)?;let mut v=vec![None;x.len()];let mut s=v.clone();let sx=(n*(n-1)/2)as f64;let sxx=(n*(n-1)*(2*n-1)/6)as f64;let den=n as f64*sxx-sx*sx;for i in n-1..x.len(){let y=&x[i+1-n..=i];let sy=y.iter().sum::<f64>();let sxy=y.iter().enumerate().map(|(j,y)|j as f64*y).sum::<f64>();let b=(n as f64*sxy-sx*sy)/den;v[i]=Some((sy-b*sx)/n as f64+b*(n-1)as f64);s[i]=Some(b)}Ok((v,s))}
pub fn adx(h:&[f64],l:&[f64],c:&[f64],n:usize)->Result<Series>{let mut plus=vec![0.;c.len()];let mut minus=plus.clone();let mut tr=plus.clone();for i in 1..c.len(){let up=h[i]-h[i-1];let dn=l[i-1]-l[i];plus[i]=if up>dn&&up>0.{up}else{0.};minus[i]=if dn>up&&dn>0.{dn}else{0.};tr[i]=(h[i]-l[i]).max((h[i]-c[i-1]).abs()).max((l[i]-c[i-1]).abs())}let p=wilder(&plus,n)?;let m=wilder(&minus,n)?;let t=wilder(&tr,n)?;let dx=(0..c.len()).map(|i|match(p[i],m[i],t[i]){(Some(a),Some(b),Some(z))if z!=0.=>Some(100.*((a-b)/z).abs()/((a+b)/z)),_=>None}).collect::<Series>();let vals=dx.iter().flatten().copied().collect::<Vec<_>>();let sm=wilder(&vals,n)?;let mut o=vec![None;c.len()];let mut j=0;for i in 0..c.len(){if dx[i].is_some(){o[i]=sm[j];j+=1}}Ok(o)}
pub fn cross(a:&[f64],b:&[f64],i:usize)->bool{i>0&&i<a.len()&&i<b.len()&&a[i-1]<=b[i-1]&&a[i]>b[i]} pub fn slope(x:&[f64],i:usize,n:usize)->Option<f64>{if n==0||i<n{None}else{Some((x[i]-x[i-n])/n as f64)}} pub fn distance_atr(a:f64,b:f64,atr:Option<f64>)->Option<f64>{atr.filter(|v|*v!=0.).map(|v|(a-b)/v)} pub fn percentile(x:&[f64],v:f64)->Option<f64>{if x.is_empty(){None}else{Some(x.iter().filter(|q|**q<=v).count()as f64/x.len()as f64)}}
pub fn session_ohlc(b:&[CanonicalM1Bar],contract:&TimeContract)->Result<(Series,Series,Series,Series)>{let m=ClockModel::from_contract(contract)?;let mut out=(vec![None;b.len()],vec![None;b.len()],vec![None;b.len()],vec![None;b.len()]);let mut day:Option<NaiveDate>=None;for(i,x)in b.iter().enumerate(){let t=m.interpret_dataset_label(x.local_timestamp)?;let d=if m.trading_day_boundary.is_some(){m.trading_day(&m.strategy_time(&t))?}else{m.session_time(&t).local.date()};if day!=Some(d){day=Some(d);out.0[i]=Some(x.open);out.1[i]=Some(x.high);out.2[i]=Some(x.low)}else{out.0[i]=out.0[i-1];out.1[i]=Some(out.1[i-1].unwrap().max(x.high));out.2[i]=Some(out.2[i-1].unwrap().min(x.low))}out.3[i]=Some(x.close)}Ok(out)}
pub fn vwap(b:&[CanonicalM1Bar],contract:&TimeContract)->Result<Series>{let m=ClockModel::from_contract(contract)?;let mut o=vec![None;b.len()];let(mut day,mut pv,mut vol)=(None,0.,0.);for(i,x)in b.iter().enumerate(){let t=m.interpret_dataset_label(x.local_timestamp)?;let d=if m.trading_day_boundary.is_some(){m.trading_day(&m.strategy_time(&t))?}else{m.session_time(&t).local.date()};if day!=Some(d){day=Some(d);pv=0.;vol=0.}let Some(v)=x.volume else{return Err(format!("VWAP requires volume at {}",x.timestamp))};pv+=(x.high+x.low+x.close)/3.*v;vol+=v;o[i]=Some(if vol==0.{0.}else{pv/vol})}Ok(o)}

#[cfg(test)] mod tests { use super::*;
 #[test] fn locked_layer1_and_transforms_have_explicit_warmups(){let x=(1..=40).map(|v|v as f64).collect::<Vec<_>>();let h=x.iter().map(|v|v+1.).collect::<Vec<_>>();let l=x.iter().map(|v|v-1.).collect::<Vec<_>>();assert_eq!(sma(&x,3).unwrap()[1],None);assert_eq!(ema(&x,3).unwrap()[2],Some(2.));assert!(atr(&h,&l,&x,3).unwrap()[2].is_some());assert_eq!(rsi(&[1.,1.,1.,1.],2).unwrap()[2],Some(50.));assert!(adx(&h,&l,&x,3).unwrap()[5].is_some());assert_eq!(er(&[1.,1.,1.],2).unwrap()[2],Some(0.));assert!(kama(&x,3,2,10).unwrap()[3].is_some());let(a,b,c)=macd(&x,3,6,2).unwrap();assert!(a[5].is_some()&&b[6].is_some()&&c[6].is_some());assert!(linear_regression(&x,3).unwrap().1[2].is_some());assert!(cci(&h,&l,&x,3).unwrap()[2].is_some());assert!(roc(&x,3).unwrap()[3].is_some());assert!(stochastic(&h,&l,&x,3,2).unwrap().1[3].is_some());assert!(bollinger(&x,3,2.).unwrap().3[2].is_some());assert!(keltner(&h,&l,&x,3,2.).unwrap().1[2].is_some());assert_eq!(highest(&x,3).unwrap()[2],Some(3.));assert_eq!(lowest(&x,3).unwrap()[2],Some(1.));assert!(cross(&[1.,3.],&[2.,2.],1));assert_eq!(slope(&x,3,3),Some(1.));assert_eq!(distance_atr(3.,1.,Some(2.)),Some(1.));assert_eq!(percentile(&x,20.),Some(0.5));assert!(sma(&x,0).is_err());}
}
