//! Internal typed indicator-artifact encoding.  Transforms do not expose booleans yet;
//! this is exercised only by the bounded test fixture below.
use std::{fs, path::Path, sync::Arc};
use arrow_array::{Array, ArrayRef, BooleanArray, Float64Array, RecordBatch, StringArray};
use arrow_schema::{DataType, Field, Schema};
use parquet::arrow::{arrow_reader::ParquetRecordBatchReaderBuilder, ArrowWriter};
use sha2::{Digest, Sha256};
use crate::series::Series;
pub type Result<T>=std::result::Result<T,String>;

pub fn identity(source:&str,specs:&str,columns:&[(String,Series)])->String { let mut h=Sha256::new();h.update(b"nora-indicator-semantic-v1");h.update(source.as_bytes());h.update(specs.as_bytes());for(name,series)in columns{h.update(name.as_bytes());match series{Series::Numeric(v)=>for x in v{match x{Some(n)=>{h.update([1]);h.update(n.to_bits().to_be_bytes())},None=>h.update([0])}},Series::Boolean(v)=>{h.update([2]);for x in v{h.update([match x{Some(false)=>0,Some(true)=>1,None=>2}])}}}}format!("{:x}",h.finalize()) }
pub fn write(path:&Path,timestamps:&[String],columns:&[(String,Series)],identity:&str)->Result<()> {let mut fields=vec![Field::new("timestamp",DataType::Utf8,false)];let mut arrays:Vec<ArrayRef>=vec![Arc::new(StringArray::from(timestamps.to_vec()))];for(name,s)in columns{match s{Series::Numeric(v)=>{fields.push(Field::new(name,DataType::Float64,true));arrays.push(Arc::new(Float64Array::from(v.clone())))},Series::Boolean(v)=>{fields.push(Field::new(name,DataType::Boolean,true));arrays.push(Arc::new(BooleanArray::from(v.clone())))}}}let mut meta=std::collections::HashMap::new();meta.insert("nora.semantic_sha256".into(),identity.into());let schema=Arc::new(Schema::new_with_metadata(fields,meta));let batch=RecordBatch::try_new(schema.clone(),arrays).map_err(|e|e.to_string())?;let mut w=ArrowWriter::try_new(fs::File::create(path).map_err(|e|e.to_string())?,schema,None).map_err(|e|e.to_string())?;w.write(&batch).map_err(|e|e.to_string())?;w.close().map_err(|e|e.to_string())?;Ok(())}
pub fn validate(path:&Path,timestamps:&[String],columns:&[(String,Series)],identity:&str)->Result<()> {let b=ParquetRecordBatchReaderBuilder::try_new(fs::File::open(path).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let s=b.schema();if s.fields().len()!=columns.len()+1||s.field(0).name()!="timestamp"||s.field(0).data_type()!=&DataType::Utf8||s.metadata().get("nora.semantic_sha256").map(String::as_str)!=Some(identity){return Err("indicator artifact schema or identity invalid".into())}for(i,(name,value))in columns.iter().enumerate(){let expected=match value{Series::Numeric(_)=>DataType::Float64,Series::Boolean(_)=>DataType::Boolean};if s.field(i+1).name()!=name||s.field(i+1).data_type()!=&expected{return Err(format!("indicator artifact type mismatch for {name}"))}}let mut row=0;for x in b.build().map_err(|e|e.to_string())?{let x=x.map_err(|e|e.to_string())?;let stamps=x.column(0).as_any().downcast_ref::<StringArray>().ok_or("timestamp type mismatch")?;for i in 0..x.num_rows(){if row>=timestamps.len()||stamps.is_null(i)||stamps.value(i)!=timestamps[row]{return Err("timestamp alignment invalid".into())}row+=1}}if row!=timestamps.len(){return Err("row count mismatch".into())}Ok(())}
pub fn write_with_metadata(path:&Path,timestamps:&[String],columns:&[(String,Series)],metadata:std::collections::HashMap<String,String>)->Result<()> {let mut fields=vec![Field::new("timestamp",DataType::Utf8,false)];let mut arrays:Vec<ArrayRef>=vec![Arc::new(StringArray::from(timestamps.to_vec()))];for(name,s)in columns{match s{Series::Numeric(v)=>{fields.push(Field::new(name,DataType::Float64,true));arrays.push(Arc::new(Float64Array::from(v.clone())))},Series::Boolean(v)=>{fields.push(Field::new(name,DataType::Boolean,true));arrays.push(Arc::new(BooleanArray::from(v.clone())))}}}let schema=Arc::new(Schema::new_with_metadata(fields,metadata));let batch=RecordBatch::try_new(schema.clone(),arrays).map_err(|e|e.to_string())?;let mut w=ArrowWriter::try_new(fs::File::create(path).map_err(|e|e.to_string())?,schema,None).map_err(|e|e.to_string())?;w.write(&batch).map_err(|e|e.to_string())?;w.close().map_err(|e|e.to_string())?;Ok(())}
pub fn validate_with_metadata(path:&Path,timestamps:&[String],columns:&[(String,Series)],metadata:&std::collections::HashMap<String,String>)->Result<()> {let identity=metadata.get("nora.semantic_sha256").ok_or("missing semantic identity")?;validate(path,timestamps,columns,identity)?;let b=ParquetRecordBatchReaderBuilder::try_new(fs::File::open(path).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;for(key,value)in metadata{if b.schema().metadata().get(key)!=Some(value){return Err(format!("indicator artifact metadata mismatch for {key}"))}}Ok(())}
#[cfg(test)]mod tests{use super::*;#[test]fn nullable_boolean_native_round_trip_and_identity(){let c=vec![("flag".into(),Series::Boolean(vec![Some(true),Some(false),None]))];let t=vec!["a".into(),"b".into(),"c".into()];let id=identity("s","[]",&c);let p=std::env::temp_dir().join(format!("bool-{}.parquet",std::process::id()));write(&p,&t,&c,&id).unwrap();validate(&p,&t,&c,&id).unwrap();let b=ParquetRecordBatchReaderBuilder::try_new(fs::File::open(&p).unwrap()).unwrap().build().unwrap().next().unwrap().unwrap();let v=b.column(1).as_any().downcast_ref::<BooleanArray>().unwrap();assert_eq!((v.value(0),v.value(1),v.is_null(2)),(true,false,true));assert_eq!(id,identity("s","[]",&c));let f=vec![("flag".into(),Series::Boolean(vec![Some(false),Some(false),None]))];let n=vec![("flag".into(),Series::Boolean(vec![Some(true),Some(false),Some(true)]))];assert_ne!(id,identity("s","[]",&f));assert_ne!(id,identity("s","[]",&n));let renamed=vec![("other".into(),c[0].1.clone())];assert_ne!(id,identity("s","[]",&renamed));let _=fs::remove_file(p);}}
