//! Ordered typed series registry for bounded indicator task evaluation.
use std::collections::HashMap;
pub type Result<T>=std::result::Result<T,String>;
#[derive(Clone,Debug,PartialEq)] pub enum Series { Numeric(Vec<Option<f64>>), Boolean(Vec<Option<bool>>) }
impl Series { pub fn len(&self)->usize{match self{Self::Numeric(x)=>x.len(),Self::Boolean(x)=>x.len()}} }
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub enum SeriesType { Numeric, Boolean }
#[derive(Clone,Debug,PartialEq,Eq)] pub struct Reference { pub series:String, pub expected:SeriesType }
impl Reference { pub fn parse(value:&serde_json::Value)->Result<Self>{let object=value.as_object().ok_or("series reference must be an object")?;if object.len()!=2||!object.contains_key("series")||!object.contains_key("type"){return Err("series reference must contain only series and type".into())}let series=object.get("series").and_then(serde_json::Value::as_str).filter(|x|!x.is_empty()).ok_or("series reference requires non-empty series")?.to_owned();let expected=match object.get("type").and_then(serde_json::Value::as_str){Some("numeric")=>SeriesType::Numeric,Some("boolean")=>SeriesType::Boolean,_=>return Err("series reference type must be numeric or boolean".into())};Ok(Self{series,expected})} }
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub enum Origin { Canonical, Derived }
#[derive(Clone,Debug)] pub struct Entry { pub name:String,pub value:Series,pub origin:Origin }
#[derive(Debug)] pub struct Registry { rows:usize, entries:Vec<Entry>, index:HashMap<String,usize> }
impl Registry { pub fn new(rows:usize)->Self{Self{rows,entries:vec![],index:HashMap::new()}} pub fn get(&self,name:&str)->Result<&Entry>{self.index.get(name).and_then(|i|self.entries.get(*i)).ok_or_else(||format!("unknown or forward series reference {name:?}"))} pub fn resolve(&self,reference:&Reference)->Result<&Entry>{let entry=self.get(&reference.series)?;let actual=match entry.value{Series::Numeric(_)=>SeriesType::Numeric,Series::Boolean(_)=>SeriesType::Boolean};if actual!=reference.expected{return Err(format!("series reference type mismatch for {:?}",reference.series))}Ok(entry)} pub fn numeric(&self,reference:&Reference)->Result<&Vec<Option<f64>>>{match &self.resolve(reference)?.value{Series::Numeric(values)=>Ok(values),Series::Boolean(_)=>Err("series reference is not numeric".into())}} pub fn boolean(&self,reference:&Reference)->Result<&Vec<Option<bool>>>{match &self.resolve(reference)?.value{Series::Boolean(values)=>Ok(values),Series::Numeric(_)=>Err("series reference is not boolean".into())}} pub fn register(&mut self,name:String,value:Series,origin:Origin)->Result<()> {self.register_all(vec![(name,value)],origin)} pub fn register_all(&mut self,values:Vec<(String,Series)>,origin:Origin)->Result<()> {let mut seen=HashMap::new();for(n,v)in &values{if n.is_empty()||self.index.contains_key(n)||seen.insert(n,()).is_some(){return Err(format!("duplicate series name {n:?}"))}if v.len()!=self.rows{return Err(format!("series {n:?} has wrong row count"))}}for(n,v)in values{self.index.insert(n.clone(),self.entries.len());self.entries.push(Entry{name:n,value:v,origin})}Ok(())} pub fn entries(&self)->&[Entry]{&self.entries} }
#[cfg(test)] mod tests {use super::*;use serde_json::json;#[test]fn ordered_and_atomic(){let mut r=Registry::new(2);r.register("close".into(),Series::Numeric(vec![Some(1.),Some(2.)]),Origin::Canonical).unwrap();assert_eq!(r.get("close").unwrap().origin,Origin::Canonical);assert!(r.get("later").is_err());assert!(r.register_all(vec![("a".into(),Series::Numeric(vec![None;2])),("a".into(),Series::Numeric(vec![None;2]))],Origin::Derived).is_err());assert!(r.entries().len()==1);assert!(r.register("bad".into(),Series::Boolean(vec![None]),Origin::Derived).is_err());}#[test]fn typed_ordered_references_fail_closed(){let mut r=Registry::new(2);r.register("close".into(),Series::Numeric(vec![Some(1.),Some(2.)]),Origin::Canonical).unwrap();let n=Reference::parse(&json!({"series":"close","type":"numeric"})).unwrap();assert_eq!(r.numeric(&n).unwrap()[0],Some(1.));assert!(r.resolve(&Reference::parse(&json!({"series":"later","type":"numeric"})).unwrap()).is_err());assert!(r.boolean(&n).is_err());r.register("flag".into(),Series::Boolean(vec![Some(true),None]),Origin::Derived).unwrap();let b=Reference::parse(&json!({"series":"flag","type":"boolean"})).unwrap();assert_eq!(r.boolean(&b).unwrap()[0],Some(true));assert!(r.numeric(&b).is_err());assert!(Reference::parse(&json!({"series":"flag","type":"wat"})).is_err());assert!(Reference::parse(&json!({"series":"flag","type":"boolean","extra":1})).is_err());assert_eq!(r.entries().iter().map(|e|e.name.as_str()).collect::<Vec<_>>(),vec!["close","flag"]);}}
