//! Narrow deterministic one-position market simulator; no intrabar or cost semantics.
use std::{fs, path::{Path,PathBuf}, sync::Arc};
use arrow_array::{Array,ArrayRef,BooleanArray,Float64Array,RecordBatch,StringArray,UInt64Array};
use arrow_schema::{DataType,Field,Schema};
use parquet::arrow::{ArrowWriter,arrow_reader::ParquetRecordBatchReaderBuilder};
use serde::{Deserialize,Serialize};
use serde_json::{json,Map,Value};
use sha2::{Digest,Sha256};

pub type Result<T>=std::result::Result<T,String>;
#[derive(Clone,Copy,Debug,Deserialize,Serialize,PartialEq,Eq)] #[serde(rename_all="lowercase")] pub enum Side{Long,Short}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)] #[serde(deny_unknown_fields)] pub struct InitialBracket{pub model:String,pub stop_offset:f64,pub target_offset:f64,pub output_path:String}
#[derive(Clone,Debug,Deserialize,Serialize,PartialEq)] #[serde(deny_unknown_fields)] pub struct Config{pub schema_version:u32,pub side:Side,pub price_column:String,pub entry_column:String,pub exit_column:String,pub position_policy:String,pub terminal_policy:String,#[serde(default,skip_serializing_if="Option::is_none")]pub initial_bracket:Option<InitialBracket>}
fn parse_config(value:&Value)->Result<Config>{let c:Config=serde_json::from_value(value.clone()).map_err(|e|format!("malformed simulator config: {e}"))?;if c.schema_version!=1{return Err("unsupported simulator config schema_version".into())}if c.price_column!="open"||c.position_policy!="one_at_a_time"||c.terminal_policy!="leave_open"||c.entry_column.is_empty()||c.exit_column.is_empty(){return Err("unsupported or invalid simulator config".into())}if let Some(b)=&c.initial_bracket{if b.model!="fixed_price_offsets_v1"{return Err("unsupported initial_bracket model".into())}if !b.stop_offset.is_finite()||!b.target_offset.is_finite()||b.stop_offset<=0.||b.target_offset<=0.{return Err("initial_bracket offsets must be finite and strictly greater than zero".into())}if b.output_path.trim().is_empty(){return Err("initial_bracket output_path must be non-empty".into())}}Ok(c)}
fn only(o:&Map<String,Value>,a:&[&str])->Result<()>{for k in o.keys(){if !a.contains(&k.as_str()){return Err(format!("unknown simulator task field {k:?}"))}}Ok(())}
fn string(o:&Map<String,Value>,k:&str)->Result<String>{o.get(k).and_then(Value::as_str).filter(|v|!v.is_empty()).map(str::to_owned).ok_or_else(||format!("missing or invalid simulator task field {k}"))}
fn out(raw:&str)->Result<PathBuf>{let p=PathBuf::from(raw);if raw.trim().is_empty()||p.exists()||p.parent().map_or(true,|x|!x.is_dir()){Err("output_path must not exist and its parent must exist".into())}else{Ok(p)}}

#[derive(Clone)] struct Market{timestamps:Vec<String>,opens:Vec<f64>}
fn reader(path:&Path)->Result<parquet::arrow::arrow_reader::ParquetRecordBatchReader>{let b=ParquetRecordBatchReaderBuilder::try_new(fs::File::open(path).map_err(|e|format!("open simulator input: {e}"))?).map_err(|e|format!("read simulator Parquet: {e}"))?;b.build().map_err(|e|format!("build simulator reader: {e}"))}
fn market(path:&Path)->Result<Market>{let mut r=reader(path)?;let mut timestamps=Vec::new();let mut opens=Vec::new();for b in &mut r{let b=b.map_err(|e|e.to_string())?;let ts=b.column_by_name("timestamp").and_then(|x|x.as_any().downcast_ref::<StringArray>()).ok_or("market requires UTF-8 timestamp")?;let op=b.column_by_name("open").and_then(|x|x.as_any().downcast_ref::<Float64Array>()).ok_or("market requires Float64 open")?;for i in 0..b.num_rows(){if ts.is_null(i){return Err("market timestamp must not be null".into())}let x=if op.is_null(i){return Err("market open must not be null".into())}else{op.value(i)};if !x.is_finite(){return Err("market open must be finite".into())}timestamps.push(ts.value(i).into());opens.push(x)}}Ok(Market{timestamps,opens})}
fn intents(path:&Path,column:&str)->Result<(Vec<String>,Vec<Option<bool>>)> {let mut r=reader(path)?;let mut ts=Vec::new();let mut values=Vec::new();for b in &mut r{let b=b.map_err(|e|e.to_string())?;let stamps=b.column_by_name("timestamp").and_then(|x|x.as_any().downcast_ref::<StringArray>()).ok_or("intent requires UTF-8 timestamp")?;let col=b.column_by_name(column).and_then(|x|x.as_any().downcast_ref::<BooleanArray>()).ok_or_else(||format!("intent requires nullable Boolean column {column}"))?;for i in 0..b.num_rows(){if stamps.is_null(i){return Err("intent timestamp must not be null".into())}ts.push(stamps.value(i).into());values.push(if col.is_null(i){None}else{Some(col.value(i))})}}Ok((ts,values))}
#[derive(Clone,Debug,PartialEq)] pub struct Trade{pub id:u64,pub side:Side,pub entry_timestamp:String,pub exit_timestamp:String,pub entry_index:u64,pub exit_index:u64,pub entry_price:f64,pub exit_price:f64,pub bars_held:u64,pub pnl:f64}
#[derive(Clone,Debug,PartialEq)] struct Open{index:usize,timestamp:String,price:f64}
#[derive(Clone,Debug,PartialEq)] struct Bracket{entry_id:u64,side:Side,entry_timestamp:String,entry_index:u64,entry_price:f64,stop:f64,target:f64}
#[derive(Clone)] struct Simulation{trades:Vec<Trade>,entries:usize,opened:Vec<Open>,ignored_entry:usize,ignored_exit:usize,terminal:Option<Open>}
fn simulate(config:&Config,market:&Market,entry:&[Option<bool>],exit:&[Option<bool>])->Result<Simulation>{if market.timestamps.len()!=entry.len()||entry.len()!=exit.len(){return Err("simulator input row counts must match".into())}let mut trades:Vec<Trade>=Vec::new();let(mut open,mut entries,mut opened,mut ignored_entry,mut ignored_exit):(Option<Open>,usize,Vec<Open>,usize,usize)=(None,0,Vec::new(),0,0);for i in 0..entry.len(){if let Some(_)=&open{if exit[i]==Some(true){if entry[i]==Some(true){ignored_entry+=1}let p=open.take().unwrap();let pnl=match config.side{Side::Long=>market.opens[i]-p.price,Side::Short=>p.price-market.opens[i]};trades.push(Trade{id:trades.len()as u64+1,side:config.side,entry_timestamp:p.timestamp,exit_timestamp:market.timestamps[i].clone(),entry_index:p.index as u64,exit_index:i as u64,entry_price:p.price,exit_price:market.opens[i],bars_held:(i-p.index)as u64,pnl});}else if entry[i]==Some(true){ignored_entry+=1}}else if entry[i]==Some(true){if exit[i]==Some(true){ignored_exit+=1}let p=Open{index:i,timestamp:market.timestamps[i].clone(),price:market.opens[i]};opened.push(p.clone());open=Some(p);entries+=1}else if exit[i]==Some(true){ignored_exit+=1}}Ok(Simulation{trades,entries,opened,ignored_entry,ignored_exit,terminal:open})}
fn side_byte(side:Side)->u8{match side{Side::Long=>1,Side::Short=>2}}
fn identity(config:&Config,market:&Market,entry:&[Option<bool>],exit:&[Option<bool>],sim:&Simulation)->String{let mut h=Sha256::new();let mut base=config.clone();base.initial_bracket=None;h.update(b"nora.market_simulator.simulate_market_v1.semantic.v2.ledger_side_v1\0");h.update(serde_json::to_string(&base).unwrap().as_bytes());h.update([0]);for i in 0..market.timestamps.len(){h.update(market.timestamps[i].as_bytes());h.update([0]);h.update(market.opens[i].to_bits().to_be_bytes());h.update([match entry[i]{Some(true)=>1,Some(false)=>0,None=>2},match exit[i]{Some(true)=>1,Some(false)=>0,None=>2}])}for t in &sim.trades{h.update(t.id.to_be_bytes());h.update([side_byte(t.side)]);h.update(t.entry_timestamp.as_bytes());h.update([0]);h.update(t.exit_timestamp.as_bytes());h.update([0]);h.update(t.entry_index.to_be_bytes());h.update(t.exit_index.to_be_bytes());h.update(t.entry_price.to_bits().to_be_bytes());h.update(t.exit_price.to_bits().to_be_bytes());h.update(t.bars_held.to_be_bytes());h.update(t.pnl.to_bits().to_be_bytes())}if let Some(p)=&sim.terminal{h.update([1]);h.update((p.index as u64).to_be_bytes());h.update(p.timestamp.as_bytes());h.update([0]);h.update(p.price.to_bits().to_be_bytes())}else{h.update([0])}format!("{:x}",h.finalize())}
fn write(path:&Path,trades:&[Trade],identity:&str)->Result<()>{let schema=Arc::new(Schema::new_with_metadata(vec![Field::new("trade_id",DataType::UInt64,false),Field::new("side",DataType::Utf8,false),Field::new("entry_timestamp",DataType::Utf8,false),Field::new("exit_timestamp",DataType::Utf8,false),Field::new("entry_index",DataType::UInt64,false),Field::new("exit_index",DataType::UInt64,false),Field::new("entry_price",DataType::Float64,false),Field::new("exit_price",DataType::Float64,false),Field::new("bars_held",DataType::UInt64,false),Field::new("gross_pnl_per_unit",DataType::Float64,false)],[("nora.semantic_sha256".into(),identity.into())].into()));let a:Vec<ArrayRef>=vec![Arc::new(UInt64Array::from(trades.iter().map(|x|x.id).collect::<Vec<_>>())),Arc::new(StringArray::from(trades.iter().map(|x|match x.side{Side::Long=>"long",Side::Short=>"short"}).collect::<Vec<_>>())),Arc::new(StringArray::from(trades.iter().map(|x|x.entry_timestamp.clone()).collect::<Vec<_>>())),Arc::new(StringArray::from(trades.iter().map(|x|x.exit_timestamp.clone()).collect::<Vec<_>>())),Arc::new(UInt64Array::from(trades.iter().map(|x|x.entry_index).collect::<Vec<_>>())),Arc::new(UInt64Array::from(trades.iter().map(|x|x.exit_index).collect::<Vec<_>>())),Arc::new(Float64Array::from(trades.iter().map(|x|x.entry_price).collect::<Vec<_>>())),Arc::new(Float64Array::from(trades.iter().map(|x|x.exit_price).collect::<Vec<_>>())),Arc::new(UInt64Array::from(trades.iter().map(|x|x.bars_held).collect::<Vec<_>>())),Arc::new(Float64Array::from(trades.iter().map(|x|x.pnl).collect::<Vec<_>>()))];let b=RecordBatch::try_new(schema.clone(),a).map_err(|e|e.to_string())?;let mut w=ArrowWriter::try_new(fs::File::create(path).map_err(|e|e.to_string())?,schema,None).map_err(|e|e.to_string())?;w.write(&b).map_err(|e|e.to_string())?;w.close().map_err(|e|e.to_string())?;Ok(())}
fn brackets(config:&Config,opened:&[Open])->Vec<Bracket>{let b=config.initial_bracket.as_ref().unwrap();opened.iter().enumerate().map(|(i,p)|{let(stop,target)=match config.side{Side::Long=>(p.price-b.stop_offset,p.price+b.target_offset),Side::Short=>(p.price+b.stop_offset,p.price-b.target_offset)};Bracket{entry_id:i as u64+1,side:config.side,entry_timestamp:p.timestamp.clone(),entry_index:p.index as u64,entry_price:p.price,stop,target}}).collect()}
fn bracket_identity(simulator_identity:&str,b:&InitialBracket,rows:&[Bracket])->String{let mut h=Sha256::new();h.update(b"nora.initial_bracket.fixed_price_offsets_v1.semantic.v1.schema.v1\0");h.update(simulator_identity.as_bytes());h.update([0]);h.update(b.stop_offset.to_bits().to_be_bytes());h.update(b.target_offset.to_bits().to_be_bytes());for r in rows{h.update(r.entry_id.to_be_bytes());h.update([side_byte(r.side)]);h.update(r.entry_timestamp.as_bytes());h.update([0]);h.update(r.entry_index.to_be_bytes());h.update(r.entry_price.to_bits().to_be_bytes());h.update(r.stop.to_bits().to_be_bytes());h.update(r.target.to_bits().to_be_bytes())}format!("{:x}",h.finalize())}
fn write_brackets(path:&Path,rows:&[Bracket],identity:&str)->Result<()>{let schema=Arc::new(Schema::new_with_metadata(vec![Field::new("entry_id",DataType::UInt64,false),Field::new("side",DataType::Utf8,false),Field::new("entry_timestamp",DataType::Utf8,false),Field::new("entry_index",DataType::UInt64,false),Field::new("entry_price",DataType::Float64,false),Field::new("initial_stop_price",DataType::Float64,false),Field::new("initial_target_price",DataType::Float64,false)],[("nora.initial_bracket_semantic_sha256".into(),identity.into())].into()));let a:Vec<ArrayRef>=vec![Arc::new(UInt64Array::from(rows.iter().map(|x|x.entry_id).collect::<Vec<_>>())),Arc::new(StringArray::from(rows.iter().map(|x|match x.side{Side::Long=>"long",Side::Short=>"short"}).collect::<Vec<_>>())),Arc::new(StringArray::from(rows.iter().map(|x|x.entry_timestamp.clone()).collect::<Vec<_>>())),Arc::new(UInt64Array::from(rows.iter().map(|x|x.entry_index).collect::<Vec<_>>())),Arc::new(Float64Array::from(rows.iter().map(|x|x.entry_price).collect::<Vec<_>>())),Arc::new(Float64Array::from(rows.iter().map(|x|x.stop).collect::<Vec<_>>())),Arc::new(Float64Array::from(rows.iter().map(|x|x.target).collect::<Vec<_>>()))];let batch=RecordBatch::try_new(schema.clone(),a).map_err(|e|e.to_string())?;let mut w=ArrowWriter::try_new(fs::File::create(path).map_err(|e|e.to_string())?,schema,None).map_err(|e|e.to_string())?;w.write(&batch).map_err(|e|e.to_string())?;w.close().map_err(|e|e.to_string())?;Ok(())}
fn publish(path:&Path,write_fn:impl FnOnce(&Path)->Result<()>)->Result<()>{let temp=path.with_file_name(format!(".{}.{}.partial",path.file_name().unwrap().to_string_lossy(),std::process::id()));if let Err(e)=write_fn(&temp){let _=fs::remove_file(&temp);return Err(e)}fs::rename(&temp,path).map_err(|e|format!("atomic publish artifact: {e}"))}
pub fn task(o:&Map<String,Value>)->Result<Value>{only(o,&["task_version","task_type","market_path","entry_intent_path","exit_intent_path","output_path","config"])?;let c=parse_config(o.get("config").ok_or("missing simulator task field config")?)?;let dst=out(&string(o,"output_path")?)?;let bracket_dst=match &c.initial_bracket{Some(b)=>{let p=out(&b.output_path)?;if p==dst{return Err("initial_bracket output_path must differ from output_path".into())}Some(p)},None=>None};let m=market(Path::new(&string(o,"market_path")?))?;let(ep,entry)=intents(Path::new(&string(o,"entry_intent_path")?),&c.entry_column)?;let(xp,exit)=intents(Path::new(&string(o,"exit_intent_path")?),&c.exit_column)?;if m.timestamps!=ep||m.timestamps!=xp{return Err("simulator timestamps must match exactly".into())}let sim=simulate(&c,&m,&entry,&exit)?;let id=identity(&c,&m,&entry,&exit,&sim);let bracket_result=match (&c.initial_bracket,&bracket_dst){(Some(b),Some(path))=>{let rows=brackets(&c,&sim.opened);let bid=bracket_identity(&id,b,&rows);publish(path,|p|write_brackets(p,&rows,&bid))?;Some((bid,path,rows.len()))},_=>None};publish(&dst,|p|write(p,&sim.trades,&id))?;let gross: f64=sim.trades.iter().map(|t|t.pnl).sum();let terminal=match &sim.terminal{Some(p)=>json!({"state":"open","side":match c.side{Side::Long=>"long",Side::Short=>"short"},"entry_index":p.index,"entry_timestamp":p.timestamp,"entry_price":p.price,"bars_open_through_final_row":m.timestamps.len()-1-p.index}),None=>json!({"state":"flat"})};let mut summary=json!({"ok":true,"task_type":"simulate_market_v1","side":match c.side{Side::Long=>"long",Side::Short=>"short"},"rows_processed":m.timestamps.len(),"entries_opened":sim.entries,"trades_closed":sim.trades.len(),"ignored_entry_intents_while_open":sim.ignored_entry,"ignored_exit_intents_while_flat":sim.ignored_exit,"terminal_state":terminal,"gross_pnl_sum":gross,"simulator_semantic_identity":id,"output_artifact_path":dst});if let Some((bid,path,n))=bracket_result{summary["initial_bracket_semantic_identity"]=json!(bid);summary["initial_bracket_rows"]=json!(n);summary["initial_bracket_output_artifact_path"]=json!(path)}Ok(summary)}

#[cfg(test)] mod tests{use super::*;fn config(side:Side)->Config{Config{schema_version:1,side,price_column:"open".into(),entry_column:"e".into(),exit_column:"x".into(),position_policy:"one_at_a_time".into(),terminal_policy:"leave_open".into(),initial_bracket:None}}fn market()->Market{Market{timestamps:vec!["0".into(),"1".into(),"2".into(),"3".into()],opens:vec![10.,11.,12.,13.]}}#[test]fn hard_coded_state_machine_cases(){let m=market();let a=simulate(&config(Side::Long),&m,&[None,Some(true),Some(true),None],&[None,None,Some(true),Some(true)]).unwrap();assert_eq!(a.trades[0],Trade{id:1,side:Side::Long,entry_timestamp:"1".into(),exit_timestamp:"2".into(),entry_index:1,exit_index:2,entry_price:11.,exit_price:12.,bars_held:1,pnl:1.});assert_eq!((a.entries,a.ignored_entry,a.ignored_exit),(1,1,1));let s=simulate(&config(Side::Short),&m,&[Some(true),None,None,None],&[None,Some(true),None,None]).unwrap();assert_eq!(s.trades[0].side,Side::Short);assert_eq!(s.trades[0].pnl,-1.);let open=simulate(&config(Side::Long),&m,&[None,None,None,Some(true)],&[None,None,None,None]).unwrap();assert_eq!(open.terminal.unwrap().index,3);let empty=simulate(&config(Side::Long),&m,&[None;4],&[None;4]).unwrap();assert!(empty.trades.is_empty());assert_eq!(identity(&config(Side::Long),&m,&[None;4],&[None;4],&empty),identity(&config(Side::Long),&m,&[None;4],&[None;4],&empty));}#[test]fn alignment_failures(){let m=market();assert!(simulate(&config(Side::Long),&m,&[None],&[None]).is_err());}}
