#!/usr/bin/env bash
#
# mt5-headless-backtest.sh  v2
# Runs MT5 backtests via config-file mode (headless).
#
# Based on proven working examples from FuscaSoftware/MT5BatchSetup
# and official MT5 documentation.
#
# Usage: mt5-headless-backtest.sh "<EA_name>" "[output_dir]"
#
# Author: Nora
# Date: 2026-07-08
#

set -euo pipefail

CONTAINER="MT5_Darwinex"

# Backtest settings
SYMBOL="GDAXI"
TIMEFRAME="H1"
MODEL="0"                # 0 = Every Tick
DEPOSIT="5000"
CURRENCY="USD"
LEVERAGE="1:20"          # Full ratio format per docs
START_DATE="2020.07.01"
END_DATE="2026.07.01"
MM_LOTS="0.01"

EA_NAME="${1:?Usage: mt5-headless-backtest.sh <EA_name> [output_dir]}"
OUTPUT_DIR="${2:-/home/gasper/trading-lab/backtests/gdaxi_2020_07_01_2026_07_01}"

# Container paths
MT5_BASE="/home/gasper/.wine/drive_c/Program Files/MetaTrader 5"
SET_DIR="${MT5_BASE}/MQL5/Profiles/Tester"

mkdir -p "${OUTPUT_DIR}"

echo "============================================"
echo "Backtest: ${EA_NAME}"
echo "Symbol: ${SYMBOL} | TF: ${TIMEFRAME} | Model: Every Tick"
echo "Date: ${START_DATE} → ${END_DATE}"
echo "Deposit: \$${DEPOSIT} | Lev: ${LEVERAGE} | mmLots: ${MM_LOTS}"
echo "============================================"

# --- Step 1: Stop watchdog and kill MT5 ---
echo "[1/5] Stopping MT5 and watchdog..."
docker exec "${CONTAINER}" bash -c 'pkill -f mt5-watchdog.sh' 2>/dev/null || true
sleep 2
docker exec "${CONTAINER}" bash -lc 'su - gasper -c "DISPLAY=:1 wineserver -k"' 2>/dev/null || true
sleep 3

# Verify dead
RUNNING=$(docker exec "${CONTAINER}" bash -c 'ps aux | grep terminal64 | grep -v grep | wc -l' 2>/dev/null || echo "0")
if [ "${RUNNING}" != "0" ]; then
    echo "[WARN] Force killing MT5..."
    docker exec "${CONTAINER}" bash -c 'kill $(ps aux | grep terminal64 | grep -v grep | awk "{print \$2}")' 2>/dev/null || true
    sleep 2
fi

# --- Step 2: Write .set file and config INI ---
echo "[2/5] Writing config files..."

# Create the Tester profiles directory if it doesn't exist
docker exec "${CONTAINER}" bash -c "mkdir -p '${SET_DIR}'"

# Write the .set file (EA input parameters)
# Format: varname=value;
docker exec "${CONTAINER}" bash -c "cat > '${SET_DIR}/${EA_NAME}.set' << 'SETEOF'
; .set file generated by Nora's backtest runner
mmLots=${MM_LOTS}||0.01||1.0||Y
mmMultiplier=1.0||1.0||1.0||Y
mmStep=0.1||0.1||0.1||Y
SETEOF"

# Write the config INI
# Key format fixes from research:
# - Expert path uses single backslashes, relative to MQL5\Experts
# - Leverage uses full ratio (1:20)
# - ExpertParameters references .set file by name (in Tester profiles dir)
# - Use /portable mode
docker exec "${CONTAINER}" bash -c "cat > '${MT5_BASE}/backtest_run.ini' << 'INIEOF'
[Tester]
Expert=\\\\GDAXI\\\\${EA_NAME}
ExpertParameters=${EA_NAME}.set
Symbol=${SYMBOL}
Period=${TIMEFRAME}
Deposit=${DEPOSIT}
Currency=${CURRENCY}
Leverage=${LEVERAGE}
Model=${MODEL}
FromDate=${START_DATE}
ToDate=${END_DATE}
ForwardMode=0
Optimization=0
OptimizationCriterion=0
ReplaceReport=1
ShutdownTerminal=1
UseLocal=1
UseRemote=0
UseCloud=0
Visual=0
INIEOF"

echo "[INFO] Config written. Content:"
docker exec "${CONTAINER}" bash -c "cat '${MT5_BASE}/backtest_run.ini'"

# --- Step 3: Launch MT5 in portable + config mode ---
echo "[3/5] Launching backtest..."

docker exec -d "${CONTAINER}" bash -lc "
    export DISPLAY=:1
    export WINEDEBUG=-all
    cd '${MT5_BASE}'
    wine terminal64.exe /portable /config:backtest_run.ini 2>/dev/null
"

echo "[INFO] Waiting for backtest to complete (max 60 min)..."

# --- Step 4: Monitor ---
echo "[4/5] Monitoring..."
MAX_WAIT=3600
WAITED=0
while [ ${WAITED} -lt ${MAX_WAIT} ]; do
    sleep 15
    WAITED=$((WAITED + 15))

    RUNNING=$(docker exec "${CONTAINER}" bash -c 'ps aux | grep terminal64 | grep -v grep | wc -l' 2>/dev/null || echo "0")
    if [ "${RUNNING}" = "0" ]; then
        echo ""
        echo "[INFO] MT5 process ended at ${WAITED}s"
        break
    fi

    if [ $((WAITED % 60)) -eq 0 ]; then
        echo "  ${WAITED}s elapsed..."
    fi
done

if [ ${WAITED} -ge ${MAX_WAIT} ]; then
    echo "[ERROR] Timeout!"
    docker exec "${CONTAINER}" bash -lc 'su - gasper -c "DISPLAY=:1 wineserver -k"' 2>/dev/null || true
fi

# --- Step 5: Find reports ---
echo "[5/5] Searching for reports..."
echo "--- New files since config creation ---"
docker exec "${CONTAINER}" bash -c "
find '${MT5_BASE}' -maxdepth 3 -type f -newer '${MT5_BASE}/backtest_run.ini' 2>/dev/null | grep -v '.mq5' | grep -v '.ex5' | head -30
echo '--- All .htm/.xml/.csv files ---'
find '${MT5_BASE}' -maxdepth 3 \( -name '*.htm' -o -name '*.xml' -o -name '*.csv' \) -newer '${MT5_BASE}/backtest_run.ini' 2>/dev/null | head -20
"

# Copy any reports to host output dir
echo "--- Copying reports to ${OUTPUT_DIR} ---"
docker exec "${CONTAINER}" bash -c "find '${MT5_BASE}' -maxdepth 3 -type f -newer '${MT5_BASE}/backtest_run.ini' \( -name '*.htm' -o -name '*.xml' -o -name '*.csv' \) -exec cp {} /home/gasper/backtest_reports/ \;" 2>/dev/null || true
docker cp "${CONTAINER}:/home/gasper/backtest_reports/." "${OUTPUT_DIR}/" 2>/dev/null || echo "[INFO] No reports to copy"

# Restart watchdog
echo "[INFO] Restarting watchdog..."
docker exec -d "${CONTAINER}" bash -c 'su - gasper -c "export DISPLAY=:1; nohup /home/gasper/.local/bin/mt5-watchdog.sh" 2>/dev/null'
sleep 2

echo ""
echo "Done. Check ${OUTPUT_DIR} for reports."
