[CmdletBinding()]
param([string]$Mode,[string]$CampaignId,[string]$LaunchId,[string]$RepositoryCommit,[string]$CaptureToolPath,[string]$CaptureToolSha256,[string]$RunnerPath,[string]$RunnerSha256,[string]$WrapperPath,[string]$WrapperSha256,[string]$LogicalCommandSha256,[string]$SubmittedCommandSha256,[int]$WrapperPid,[string]$WrapperStartUtc,[string]$EvidenceRoot,[int]$CaptureCount)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$base=Join-Path $EvidenceRoot 'firewall-campaigns';New-Item -ItemType Directory -Path $base -Force|Out-Null
$cr=Join-Path $base $CampaignId;New-Item -ItemType Directory -Path $cr -ErrorAction Stop|Out-Null
foreach($d in 'claims','captures','receipts','temporary','partials'){New-Item -ItemType Directory -Path (Join-Path $cr $d) -ErrorAction Stop|Out-Null}
$actualParent=(Get-CimInstance Win32_Process -Filter ('ProcessId='+$PID)).ParentProcessId
$owner=[ordered]@{schema_version='nora.phase2_firewall_campaign_v1';campaign_id=$CampaignId;launch_id=$LaunchId;host_identity=[Security.Principal.WindowsIdentity]::GetCurrent().Name;windows_user=[Security.Principal.WindowsIdentity]::GetCurrent().Name;owner_pid=$PID;owner_process_start_utc=((Get-CimInstance Win32_Process -Filter ('ProcessId='+$PID)).CreationDate);parent_process_id=999999;launcher_path=$PSCommandPath;normalized_command_sha256=('0'*64);repository_commit=$RepositoryCommit;runner_path=$RunnerPath;runner_sha256=$RunnerSha256;capture_tool_path=$CaptureToolPath;capture_tool_sha256=$CaptureToolSha256;expected_capture_count=$CaptureCount;capture_interval_seconds=0;created_utc=(Get-Date).ToUniversalTime().ToString('o');owner_token_sha256=('1'*64);state='reserved';wrapper_path=$WrapperPath;wrapper_sha256=$WrapperSha256;logical_command_sha256=$LogicalCommandSha256;submitted_command_sha256=$SubmittedCommandSha256;wrapper_pid=$WrapperPid;wrapper_start_utc=$WrapperStartUtc;campaign_executable_path=(Get-CimInstance Win32_Process -Filter ('ProcessId='+$PID)).ExecutablePath;campaign_command_line=(Get-CimInstance Win32_Process -Filter ('ProcessId='+$PID)).CommandLine}
$t=Join-Path $cr 'owner.json.partial';[IO.File]::WriteAllText($t,($owner|ConvertTo-Json -Depth 30 -Compress),[Text.UTF8Encoding]::new($false));[IO.File]::Move($t,(Join-Path $cr 'owner.json'))
Start-Sleep -Seconds 20
