[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$HelperPath)
$ErrorActionPreference='Stop'
function Put-Json([string]$Path,$Value){$Value|ConvertTo-Json -Depth 20 -Compress|Set-Content -LiteralPath $Path -Encoding utf8 -NoNewline}
function Invoke-Inventory([string]$Root){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$out=@(& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $HelperPath -Mode inventory -EvidenceRoot $Root -QualificationId 'synthetic-operator-state' 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;[ordered]@{code=$code;output=($out -join '')}}
$base=Join-Path $env:TEMP ('nora-operator-state-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path (Join-Path $base 'jobs') -Force|Out-Null;New-Item -ItemType Directory -Path (Join-Path $base 'reconciliations') -Force|Out-Null
try {
 $completed=Join-Path $base 'jobs\completed.json';Put-Json $completed @{schema_version='nora.phase2_persistent_evidence_runner_v1';run_identifier='completed-1';state='completed';preflight_kind='offline_cache'}
 $prepared=Join-Path $base 'jobs\prepared-1.json';Put-Json $prepared @{schema_version='nora.phase2_persistent_evidence_runner_v1';run_identifier='prepared-1';state='prepared';preflight_kind='offline_cache'}
 $raw=[IO.File]::ReadAllBytes($prepared);$sha=([Security.Cryptography.SHA256]::Create().ComputeHash($raw)|ForEach-Object{$_.ToString('x2')})-join'';$rdir=Join-Path $base 'reconciliations\prepared-1.published';New-Item -ItemType Directory -Path $rdir|Out-Null;[IO.File]::WriteAllBytes((Join-Path $rdir 'original-job.json'),$raw);Put-Json (Join-Path $rdir 'reconciliation.json') @{schema_version='nora.phase2_prelaunch_reconciliation_v1';run_identifier='prepared-1';classification='ABANDONED_PRE_LAUNCH_NO_CONTAINMENT';accepted=$false;original_job_sha256=$sha;original_job_size=$raw.Length}
 $mutated=@{schema_version='nora.phase2_persistent_evidence_runner_v1';run_identifier='prepared-1';state='abandoned';preflight_kind='offline_cache';reconciliation_record_path=(Join-Path $rdir 'reconciliation.json')};Put-Json $prepared $mutated
 $safe=Invoke-Inventory $base;if($safe.code -ne 0 -or $safe.output -notmatch '"unresolved_prepared_job_count":0' -or $safe.output -notmatch '"current_job_changed_after_reconciliation":true'){throw 'immutable raw binding or mutation-after-publication failed'}
 Remove-Item -LiteralPath $rdir -Recurse -Force;$unresolved=Invoke-Inventory $base;if($unresolved.code -eq 0 -or $unresolved.output -notmatch 'reconciliation original job missing'){throw 'missing immutable original was not rejected'}
 Put-Json $prepared @{schema_version='nora.phase2_persistent_evidence_runner_v1';run_identifier='prepared-1';state='prepared';Keys=@('state');Values=@('completed')};$contradict=Invoke-Inventory $base;if($contradict.code -eq 0){throw 'contradictory state passed'}
 $legacy=Join-Path $base 'jobs\legacy-1.json';Remove-Item -LiteralPath $prepared -Force;$legacyRaw=[Text.Encoding]::UTF8.GetPreamble()+[Text.Encoding]::UTF8.GetBytes('{"schema_version":"nora.phase2_persistent_evidence_runner_v1","Keys":["run_identifier","state","preflight_kind"],"Values":["legacy-1","prepared","offline_cache"]}');[IO.File]::WriteAllBytes($legacy,$legacyRaw);$legacyDir=Join-Path $base 'reconciliations\legacy-1.published';New-Item -ItemType Directory -Path $legacyDir|Out-Null;[IO.File]::WriteAllBytes((Join-Path $legacyDir 'original-job.json'),$legacyRaw);$legacySha=([Security.Cryptography.SHA256]::Create().ComputeHash($legacyRaw)|ForEach-Object{$_.ToString('x2')})-join'';Put-Json (Join-Path $legacyDir 'reconciliation.json') @{schema_version='nora.phase2_prelaunch_reconciliation_v1';run_identifier='legacy-1';classification='ABANDONED_PRE_LAUNCH_NO_CONTAINMENT';accepted=$false;original_job_sha256=$legacySha;original_job_size=$legacyRaw.Length};$legacyResult=Invoke-Inventory $base;if($legacyResult.code -eq 0 -and $legacyResult.output -match '"reconciled_historical_prepared_count":1'){$legacyPass='PASS'}else{throw 'legacy nested Keys/Values binding failed'}
 [ordered]@{verdict='PASS';safe_reconciled='PASS';mutation_after_publication='PASS';legacy_nested_keys_values=$legacyPass;unresolved_prepared='FAIL_AS_EXPECTED';contradictory_reconciliation='FAIL_AS_EXPECTED'}|ConvertTo-Json -Compress
} finally {Remove-Item -LiteralPath $base -Recurse -Force -ErrorAction SilentlyContinue}
